- agenta-web/src/components/Sidebar/Sidebar.tsx
Clicking on help now forwards to docs.agenta.ai
> added link to docs.agenta.ai

- agenta-cli/agenta/cli/main.py
- agenta-cli/poetry.lock
- agenta-cli/pyproject.toml
Added --version and -v to cli
Version bump
> Version cmd

- agenta-backend/agenta_backend/config.py
- agenta-backend/agenta_backend/routers/container_manager.py
- agenta-backend/agenta_backend/services/docker_utils.py
- agenta-cli/agenta/cli/helper.py
- agenta-cli/agenta/cli/main.py
- agenta-cli/agenta/cli/variant_commands.py
- agenta-cli/agenta/client/client.py
- agenta-cli/agenta/config.py
- agenta-cli/agenta/config.toml
- agenta-cli/agenta/docker/docker_utils.py
- agenta-cli/pyproject.toml
- docker-compose.prod.yml
- docker-compose.yml
- docs/conceptual/concepts.mdx
- docs/reference/agenta-cli.mdx
- One-click backend deployment in remote and local
- Agenta init now asks for the config (remote or local) and then works accordingly
- Updated documentation accordingly
Closes #74
> Cli deploy to prod

- docs/introduction.mdx
Hi @mmabrouk, I removed some grammatical errors in the introduction section of the documentation.
> Docs: modify introduction section in documentation

- agenta-web/src/components/Sidebar/Sidebar.tsx
- Removed elements soon and avatar that can't be clicked
Close #88
> removed soon elements

- docs/conceptual/concepts.mdx
Hi @mmabrouk,
For the sake of clarity, I changed "Language Model (llm)" to "Large Language Model (LLM)".
> Modified app introduction in conceptual guides

- agenta-web/src/components/Playground/ViewNavigation.tsx
Hi @mmabrouk, this PR closes #85
> Added button to delete variants that are not running

- agenta-backend/agenta_backend/routers/app_variant.py
Hi @mmabrouk x @aakrem this PR closes #84
> Added logic to remove the failing variant from the backend

- examples/sales_transcript_summarizer/README.md
- examples/sales_transcript_summarizer/app.py
- examples/sales_transcript_summarizer/requirements.txt
Hi @mmabrouk,
This PR adds the Sales Transcript Summarizer LLM (Large Language Model) app to the examples folder. The Sales Transcript Summarizer is an AI-powered application that can generate concise summaries of sales transcripts, highlighting the main talking points and key insights from the conversations.
Based on the requirements that were provided, I implemented the following features:
- Truncation strategy to handle enormous sales transcripts efficiently and ensure accurate summarization with the context size limit
- Summarization logic to provide shorter and better-focused summaries of lengthy sales conversations. Although, in my case, for the sake of simplicity, I used the truncated text.
- Context size handling: Employed multiple strategies to manage the context size of the LLM, …
> Added the sales_transcript_summarizer LLM app to the examples folder

- agenta-web/src/components/Playground/TestContextProvider.tsx
- agenta-web/src/components/Playground/VersionTabs.tsx
- agenta-web/src/components/Playground/Views/TestView.tsx
What: https://github.com/Agenta-AI/agenta/issues/106
How:
Create Test context that has array of objects as stored value.
Wrap the Navigation tabs with context
Add values to TestView component and update the setting of the values function.
Note: I forgot to turn of the formatting on save so the files are formatted and might not be easy to review.
Note2: It is advised to optimise the inputs so we debounce the change of input value until the user stops typing. This will get rid off a lot of unnecessary rerenders.
https://github.com/Agenta-AI/agenta/assets/8658374/3528b9eb-8508-492f-8f02-95b444093ebd
> Make the test cases work with the same values on all variants

- docs/installation/local-installation/local-installation.mdx
> Minor fix for #122

- agenta-cli/agenta/cli/main.py
Hi @mmabrouk,
This PR closes issue #109
> Modified reg.match pattern

- agenta-web/src/components/TestSetTable/TestSetTable.tsx
> Make 'Save Test Set' Button Visible - UI Improvement

- agenta-web/src/components/Playground/Views/TestView.tsx
I missed that Test view component uses the same interface as box component.
Since they now behave in different way I have fixed the problem with interfaces.
> Minor fix for the interface difference between components

- agenta-web/src/components/TestSetTable/InsertTestSetNameModal.tsx
- agenta-web/src/components/TestSetTable/TestSetTable.tsx
Hi @mmabrouk,
This PR closes #111
> Disable creation of test set with empty names

- examples/sales_call_question_answering/app.py
- examples/sales_call_question_answering/requirements.txt
@mmabrouk This PR responds to #129 by implementing an example application in LlamaIndex for transcript analysis based on a user question.
> Example application: transcript analysis with embedding

- agenta-cli/agenta/cli/variant_commands.py
Hi @mmabrouk,
This PR closes #135
> Improve Exception Handling for Agenta Backend Connection

- agenta-cli/agenta/cli/main.py
What does this PR do? It adds a version check feature to the "agenta" CLI, notifying users when a new version is available on PyPI.
This PR will close #148
> Add version check for CLI update

- agenta-web/src/components/DynamicCodeBlock/DynamicCodeBlock.tsx
Hi @mmabrouk,
This PR closes #157. Please, let me know if there's anything I'm not doing right!
> Fix: Code snippets now shows when you click on 'Create a Test Set with API'

- agenta-web/src/components/Playground/VersionTabs.tsx
- agenta-web/src/lib/Types.ts
Hi @mmabrouk,
Let me know if there's something I'm not doing right! Merging this PR closes #153.
> Fix - removed warnings in playground page

- agenta-web/src/components/AppSelector/AppCard.tsx
- agenta-web/src/components/DynamicCodeBlock/DynamicCodeBlock.tsx
- agenta-web/src/components/Evaluations/Evaluations.tsx
- agenta-web/src/components/Playground/VersionTabs.tsx
- agenta-web/src/lib/Types.ts
@aybruhm I took the first part of #160 and created a PR out of it + reformatted using npm run format-fix
> Partial solution from #160

- agenta-web/src/components/Sidebar/Sidebar.tsx
I've replaced the divs in the sidebar with Next's Link component so that the menu items can easily be opened in new tab/windows. @mmabrouk  please review.
> Update sidebar menu items to allow opening in new tab

- agenta-web/src/components/Layout/Layout.tsx
- agenta-web/src/components/Sidebar/Sidebar.tsx
> Decouple sidebar scroll from page content scroll

- agenta-web/src/components/DynamicCodeBlock/CodeBlock.tsx
- agenta-web/src/components/DynamicCodeBlock/DynamicCodeBlock.tsx
- agenta-web/src/components/EvaluationTable/EvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/EvaluationTableWithChat.tsx
- agenta-web/src/components/EvaluationTable/ExactMatchEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx
- agenta-web/src/components/Layout/Layout.tsx
- agenta-web/src/components/Layout/ThemeContextProvider.tsx
- agenta-web/src/components/Logo/Logo.tsx
- agenta-web/src/components/Playground/Views/TestView.tsx
- agenta-web/src/components/Sidebar/Sidebar.tsx
- agenta-web/src/components/TestSetTable/TestSetTable.tsx
- agenta-web/src/pages/_app.tsx
> Support Dark mode

- agenta-backend/agenta_backend/routers/app_evaluation_router.py
- agenta-web/src/components/Evaluations/EvaluationErrorModal.tsx
- agenta-web/src/components/Evaluations/Evaluations.tsx
This fixes issue #173
@mmabrouk please review.
> Handle errors when running evaluation with test set with wrong column names

- docs/howto/how-to-debug.mdx
Hi @mmabrouk,
Regarding the [PR](https://github.com/Agenta-AI/agenta/pull/176) that I raised three days ago, I have added a guide to troubleshoot the application if a gateway error occurs.
> Improvement - added troubleshooting guide for gateway error

- agenta-backend/db/migration/mongodb/m_001_dataset_to_testset.py
- agenta-backend/db/migration/mongodb/m_002_comparision_table_dataset_field_to_testcase.py
- agenta-backend/db/migration/mongodb/run_migrations.py
- docs/migration/migration.mdx
Add:
1. Migration added to replace dataset field in comparison Table to testset
> feat: adding migration to replace dataset field to testset field in comparision table

- agenta-web/src/components/Playground/VersionTabs.tsx
> Fix issues with delete variant

- agenta-cli/agenta/sdk/agenta.py
- agenta-cli/agenta/sdk/types.py
- agenta-web/src/components/Playground/Views/ParametersView.tsx
- agenta-web/src/lib/Types.ts
- agenta-web/src/lib/helpers/openapi_parser.ts
- docs/tutorials/your-first-llm-app.mdx
- examples/sales_transcript_summarizer/app.py
Hi @mmabrouk,
Tasks that have been worked on:
> Feat - introduce multichoice param

- agenta-web/src/components/TestSetTable/TestsetTable.tsx
UI bug #220: removes redirects and adds feedback feature.
> Save test set redirects to the test set view

- agenta-web/src/components/ApiKeys/ApiKeys.tsx
- agenta-web/src/components/Sidebar/Sidebar.tsx
- agenta-web/src/lib/helpers/utils.ts
- agenta-web/src/pages/apps/[app_name]/apikeys/index.tsx
What:
close #206 
How:
Create new tab called API keys
Add new apikeys page
Create new component ApiKeys
Create functions to save openAI keys to local storage
> Create api tokens tab and page

- agenta-web/package-lock.json
- agenta-web/package.json
- agenta-web/src/components/TestSetTable/EditRowModal.tsx
- agenta-web/src/components/TestSetTable/TestsetTable.tsx
- agenta-web/src/hooks/useResizeObserver.ts
- agenta-web/src/lib/helpers/utils.ts
- agenta-web/src/pages/_app.tsx
> feat: focused editing mode in test sets

- agenta-web/src/components/Playground/LoadTestsModal.tsx
- agenta-web/src/components/Playground/Views/TestView.tsx
- agenta-web/src/pages/_app.tsx
> Add new "Run all" button in the playground

- agenta-web/src/components/ApiKeys/ApiKeys.tsx
What: 
fix #309 
How:
Use antD message api
> Add message on LLM key save and delete 

- agenta-web/src/components/TestSetTable/TestsetTable.tsx
improve the ui of view edit testset
> Testset UI

- agenta-web/src/components/Evaluations/Evaluations.tsx
> Bug: All evaluations do not work without OpenAI API key

- agenta-web/src/components/Layout/Layout.tsx
> Excessive footer height in the evaluation view

- agenta-web/src/pages/apps/[app_name]/testsets/index.tsx
- agenta-web/src/styles/globals.css
> Improve ux in Testset view by modifying the cursor type on hover

- agenta-web/src/components/Evaluations/EvaluationsList.tsx
> warnings evaluation page

- agenta-backend/agenta_backend/services/container_manager.py
- fix for macos arch
- reformatting
> added macos arch

- README.md
- agenta-backend/agenta_backend/routers/evaluation_router.py
- agenta-backend/agenta_backend/services/evaluation_service.py
- agenta-web/src/components/Sidebar/Sidebar.tsx
- examples/chat_models/app.py
- examples/transcript_qa_llama/app.py
- examples/translator/app.py
@aakrem Checked out the licensing agreement. They only require to have the attribution in the readme.
> Remove attribution from app and add to readme

- agenta-web/src/components/Layout/Layout.tsx
issue #352: Fixes Footer position in Firefox browser
> [Bug] Footer in firefox is not in the right place

- agenta-web/src/pages/apps/[app_name]/testsets/index.tsx
issue #358: Fixes testset navigation issue
> Improve navigation to test set

- agenta-web/src/components/Evaluations/Evaluations.tsx
issue #321: Displays Image in dark mode
> Images are not displayed in dark mode

- agenta-backend/agenta_backend/routers/evaluation_router.py
- agenta-backend/agenta_backend/services/evaluation_service.py
- agenta-cli/agenta/sdk/agenta.py
- agenta-cli/agenta/sdk/types.py
- agenta-web/src/lib/helpers/openapi_parser.ts
- agenta-web/src/lib/services/api.ts
Added default keys parameter to DictInput for preset key initialization.
Closes #329 
Please review the changes and provide feedback. Let me know if any further adjustments are needed.
> Feat - add default to dictinput

- agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx
issue #401: modifies digits after decimal
> Round similarity to 2 digits after decimal

- agenta-web/src/components/Playground/ViewNavigation.tsx
issue #360: Fixed issue with page refresh on saving variant in playground.
> Save variant triggers refresh in playground and loss of data

- agenta-backend/agenta_backend/main.py
- agenta-backend/agenta_backend/routers/app_variant.py
- agenta-backend/agenta_backend/routers/container_router.py
- agenta-backend/agenta_backend/routers/evaluation_router.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/container_manager.py
- agenta-backend/agenta_backend/services/db_manager.py
- agenta-backend/agenta_backend/services/evaluation_service.py
- agenta-web/package-lock.json
- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx
- agenta-web/src/lib/Types.ts
This PR addresses the following issues:
- Start app from the template does not work anymore
- Deleting apps started from the template seems not to work too
In addition to this resolved issue, I created logic to remove old templates from the db and increase the wait time to route the user to the playground when the variant container starts to run.
**More context for "remove old templates from the db":**
When a template is removed from our DockerHub account, the backend will still retain the template because it has already been saved in our database. I have created a function to check at startup, while pulling the templates, to see if any templates have been deleted. If so, the function proceeds to remove them from our database.
Hi, @mmabrouk. Kindly review and offer feedback if there is …
> Enhancement - Templates from UI

- agenta-web/src/components/TestSetTable/TestsetTable.tsx
- agenta-web/src/lib/Types.ts
- agenta-web/src/lib/helpers/variantHelper.ts
- agenta-web/src/lib/services/api.ts
- agenta-web/src/pages/_app.tsx
Autofill column names with variant inputs
Resolves #372
> 372 | Feature: Autofill testset column names with variant inputs

- agenta-web/src/components/AppSelector/modals/WriteOwnAppModal.tsx
> Youtube video keep running in app view even after you close the modal

- agenta-web/src/components/Playground/VariantRemovalWarningModal.tsx
- agenta-web/src/components/Playground/VersionTabs.tsx
issue #421: Fixes navigation bug on delete
> Bug: deleting a variant causes navigation to the app selection screen

- .github/workflows/lint.yml
- agenta-web/.eslintrc.json
- agenta-web/package-lock.json
- agenta-web/package.json
- agenta-web/src/components/AppSelector/AppCard.tsx
- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/DynamicCodeBlock/DynamicCodeBlock.tsx
- agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/AICritiqueEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/ExactMatchEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx
- agenta-web/src/components/Evaluations/Evaluations.tsx
- agenta-web/src/components/Playground/VersionTabs.tsx
- agenta-web/src/components/Playground/ViewNavigation.tsx
- agenta-web/src/components/Playground/Views/ParametersCards.tsx
- agenta-web/src/components/Playground/Views/ParametersView.tsx
- agenta-web/src/components/Playground/Views/TestView.tsx
- agenta-web/src/components/Results/ResultsPlots/ResultsPlots.tsx
- agenta-web/src/components/TestSetTable/EditRowModal.tsx
- agenta-web/src/components/TestSetTable/TestsetTable.tsx
- agenta-web/src/lib/Types.ts
- agenta-web/src/lib/helpers/openapi_parser.ts
- agenta-web/src/lib/hooks/useVariant.ts
- agenta-web/src/lib/services/api.ts
- agenta-web/src/lib/services/evaluations.ts
- agenta-web/src/lib/transformers.ts
- agenta-web/src/pages/apps/[app_name]/endpoints/index.tsx
- added missing types
- fixed lint errors
- created `useVariants` hook to be used with variants array in evaluation tables
- successful build creation
Resolves #407
> #407 | Fix: NextJS build issues

- agenta-backend/agenta_backend/__init__.py
- agenta-backend/agenta_backend/main.py
- agenta-backend/agenta_backend/services/docker_utils.py
- agenta-backend/agenta_backend/services/selectors.py
- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/config/frontendConfig.ts
- agenta-web/src/pages/auth/[[...path]].tsx
This PR eliminates the unhandled runtime error on the apps page.
Kindly review and provide feedback, if any.
> Cleanup - handle fetchApps errors

- agenta-backend/agenta_backend/__init__.py
- agenta-backend/agenta_backend/main.py
- agenta-backend/agenta_backend/services/commoners.py
- agenta-backend/agenta_backend/services/selectors.py
- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/Sidebar/Sidebar.tsx
This PR addresses the following issues:
Kindly review and provide feedback, if any.
> Enhancement - thirdparty account(s) creation

- agenta-web/src/components/TestSetTable/TestsetTable.tsx
issue #443: Fixes bug when editing cells in Testsets
> Weird behaviour when editing cells in Testsets

- agenta-backend/agenta_backend/models/db_models.py
- agenta-backend/agenta_backend/routers/app_variant.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/db_manager.py
This PR resolves the error: referenced document not found.
For a seamless migration, it is advisable for users to delete both the MongoDB container and volume.
> Bug Fix - odmantic migration error

- .github/workflows/publish.yml
Fixed problem with workflow being unable to change the directory to ../../agenta-cli.
> update: fix path to use submodule

- .github/workflows/publish.yml
This PR fixes all issues with publishing agenta to PyPI on version change. 
@mmabrouk
> feat: finally publish to PyPI on version change

- agenta-backend/agenta_backend/models/api/api_models.py
- agenta-backend/agenta_backend/routers/container_router.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/container_manager.py
- agenta-backend/agenta_backend/services/db_manager.py
- agenta-backend/agenta_backend/services/docker_utils.py
- agenta-web/src/components/Playground/ViewNavigation.tsx
- agenta-web/src/lib/services/api.ts
This PR attaches the user's unique ID to the variant container.
Kindly review and provide feedback, if any.
> Ehancement - start variant container

- agenta-web/src/components/Sidebar/Sidebar.tsx
> Clicking on the logo should navigate to /app

- .github/workflows/build-check.yml
> ci/cd: added github actions for agenta-web

- agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
> [A/B Testing Eval] Evaluation Type name is missing

- agenta-web/src/components/Evaluations/AutomaticEvaluationResult.tsx
> [Exact Match Eval] Average score in Automatic Evaluation Results is displaying Nan%

- agenta-cli/agenta/templates/compose_email/README.md
- agenta-cli/agenta/templates/compose_email/app.py
- agenta-cli/agenta/templates/compose_email/env.example
- agenta-cli/agenta/templates/compose_email/requirements.txt
- agenta-cli/agenta/templates/compose_email/template.toml
- examples/compose_email/app.py
- examples/compose_email/requirements.txt
This PR addresses #303 in part. 
The template app was created in;
- Agenta-Cli
- Example folder.
> #303/enhancement/create template app to compose email

- agenta-web/package-lock.json
- agenta-web/src/pages/apps/[app_name]/testsets/index.tsx
FIx: Display "Start an evaluation" only when there are testsets #509
> Show "Start an evaluation" when there are testsets

- agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
> Fix - A/B testing results notification is shown multiple times

- agenta-web/src/components/Evaluations/Evaluations.tsx
> Warning for missing selection of the second variant is absent

- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/Layout/Layout.tsx
> Add a "star us" button

- agenta-cli/agenta/templates/extract_data_to_json/README.md
- agenta-cli/agenta/templates/extract_data_to_json/app.py
- agenta-cli/agenta/templates/extract_data_to_json/env.example
- agenta-cli/agenta/templates/extract_data_to_json/requirements.txt
- agenta-cli/agenta/templates/extract_data_to_json/template.toml
- examples/extract_data_to_json/README.md
- examples/extract_data_to_json/app.py
- examples/extract_data_to_json/env.example
- examples/extract_data_to_json/requirements.txt
- examples/extract_data_to_json/template.toml
This LLM App uses OpenAI functions in LangChain to extract data from text.
> create extract data llm app

- agenta-web/src/components/Layout/ThemeContextProvider.tsx
- agenta-web/src/components/Sidebar/Sidebar.tsx
Resolves #537
@aakrem Please inform me if there are any necessary changes that need to be made.
> Automatic theme change on the system's theme fixed

- agenta-cli/agenta/cli/variant_commands.py
- agenta-cli/agenta/client/client.py
> Improved error messaging in both start_variant and in the client

- agenta-web/src/components/Playground/VersionTabs.tsx
- issue #547 
@mmabrouk please let me know if this is a good fix!
> Feat - Add a "Refresh" Button for Dynamic Variant Updates

- agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/AICritiqueEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/ExactMatchEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx
- agenta-web/src/components/SecondaryButton/SecondaryButton.tsx
- agenta-web/src/lib/helpers/evaluate.ts
> Fea: Export evaluation results from EvaluationTableView

- agenta-web/src/components/Playground/NewVariantModal.tsx
Rename `handleInputChange` to `handleVariantNameChange`
Reference; https://github.com/Agenta-AI/agenta/pull/578#discussion_r1322889191
> refactor: rename unclear function for better clarity

- agenta-web/prod.Dockerfile
fixed prod.Dockerfile to not omit dev dependencies
> Fixed prod build for agenta-web

- agenta-web/src/components/Evaluations/CustomPythonCode.tsx
> Fix: Code Evaluation View UI

- agenta-web/src/components/EvaluationTable/AICritiqueEvaluationTable.tsx
> Fix AI Critique Evaluation page Visibility issue

- agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx
> Fix: Similarity-match-threshold state

- agenta-web/src/components/Evaluations/Evaluations.tsx
In Evaluations Page: A/B Testing image accidentally removed and merged into the main branch.
> Restore removed image

- agenta-backend/agenta_backend/models/db_models.py
> updated db models schema for ee db schema

- agenta-web/src/components/Playground/VersionTabs.tsx
- agenta-web/src/components/Playground/Views/PublishVariantModal.tsx
- agenta-web/src/lib/helpers/variantHelper.ts
- agenta-web/src/lib/services/api.ts
- agenta-web/src/pages/apps/[app_name]/endpoints/index.tsx
- fixed build issues
- code review points addressed
- removed redundant logs
> SDK V2 - Fixed FE issues

- agenta-web/src/components/AppSelector/AppCard.tsx
Re-Route Card View
Issue -  #525
> fix: Improve App card ui/ux #525

- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/routers/evaluation_router.py
- agenta-backend/agenta_backend/services/evaluation_service.py
This PR addresses the following refactor:
> Enhancement - Refactor custom evaluation endpoints

- agenta-web/cypress/e2e/app-navigation.cy.ts
- agenta-web/cypress/e2e/testset.cy.ts
- agenta-web/src/components/ApiKeys/ApiKeys.tsx
- agenta-web/src/components/Evaluations/Evaluations.tsx
- agenta-web/src/components/Playground/Views/ParametersView.tsx
- agenta-web/src/pages/apps/[app_name]/endpoints/index.tsx
- Enhancement: Cypress Test Suite for Navigating Through App Pages.
Issue #674
> Cypress: navigating through app pages without error

- agenta-web/cypress/e2e/app-navigation.cy.ts
- agenta-web/src/components/Sidebar/Sidebar.tsx
> [App Navigation]: Cypress Test Failure After Refactoring

- agenta-web/cypress/e2e/playground.cy.ts
> [Playground]: Cypress Test Failure After Refactoring

- agenta-web/src/components/Layout/Layout.tsx
- agenta-web/src/components/Layout/ThemeContextProvider.tsx
- Re-enable system theme option
- Fixed an issue of app theme not changing dynamically based on system theme (when system theme is selected)
> Re enable system theme option

- agenta-web/src/components/AppSelector/AppCard.tsx
- agenta-web/src/components/Playground/Playground.tsx
- agenta-web/src/lib/hooks/useVariant.ts
fixed FE error while removing a variant with deleted container
Resolves #730
> 370 | Fix: Deleting variant of a detached container

- agenta-web/.env.local.example
- agenta-web/dev.Dockerfile
- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/Evaluations/Evaluations.tsx
- agenta-web/src/lib/helpers/utils.ts
- setup_agenta_web.sh
> fallback to .env.local when reading api key

- agenta-backend/agenta_backend/main.py
- agenta-backend/agenta_backend/models/api/api_models.py
- agenta-backend/agenta_backend/models/db_models.py
- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/routers/container_router.py
- agenta-backend/agenta_backend/routers/environment_router.py
- agenta-backend/agenta_backend/routers/evaluation_router.py
- agenta-backend/agenta_backend/routers/observability_router.py
- agenta-backend/agenta_backend/routers/organization_router.py
- agenta-backend/agenta_backend/routers/testset_router.py
- agenta-backend/agenta_backend/routers/user_profile.py
- agenta-backend/agenta_backend/routers/variants_router.py
- agenta-backend/agenta_backend/services/auth_helper.py
- agenta-backend/agenta_backend/services/selectors.py
- agenta-web/.env
- agenta-web/cypress/e2e/app-navigation.cy.ts
- agenta-web/cypress/e2e/playground.cy.ts
- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/CopyButton/CopyButton.tsx
- agenta-web/src/components/Evaluations/Evaluations.tsx
- agenta-web/src/components/pages/settings/Secrets/Secrets.tsx
- agenta-web/src/hooks/useLoading.ts
- agenta-web/src/lib/helpers/copyToClipboard.ts
- agenta-web/src/lib/helpers/featureFlag.ts
- agenta-web/src/pages/apikeys.tsx
- agenta-web/src/pages/apps/[app_id]/apikeys/index.tsx
- agenta-web/src/pages/settings/index.tsx
- rename api keys to secrets
- sideffects for ee api keys
> Side Effects: EE API Keys

- agenta-web/src/lib/hooks/useVariant.ts
> fix: useEffect dependencies inside useVariant

- docs/contributing/getting-started.mdx
This should resolve issue #736
> docs: add guide on how to run backend tests

- agenta-cli/agenta/cli/helper.py
- agenta-cli/agenta/cli/variant_commands.py
- agenta-cli/agenta/client/client.py
Improved the CLI to cover edge cases such as when a user deletes an app from the WebUI and attempts to serve or perform an action on it from the CLI
> cover edge cases and add error tracing for them

- agenta-backend/agenta_backend/services/app_manager.py
- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/AppSelector/modals/CreateAppStatusModal.tsx
- agenta-web/src/lib/services/api.ts
- Removed notification statuses during app creation
- Increased timeout duration for both oss and ee
- App creation status modal
- Status steps with loading, success and error states
- Retry on error
- Retry on timeout
- Show warning when takes too much time
Resolves: https://github.com/Agenta-AI/agenta_ee/issues/122
> Feature: improve loader and status update for new app creation

- agenta-web/src/components/AppSelector/modals/WriteOwnAppModal.tsx
This PR adds the correct command to the copy button and the UI for adding the OPEN_AI environment variable to the agenta-web .env file and also for the git clone command. 
Issue #775
> bugfix: errors in commands on WriteOwnApp page

- agenta-backend/agenta_backend/models/db_models.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-cli/agenta/client/client.py
Inject an api key when running new container
> Inject api key sdkv2

- agenta-backend/agenta_backend/routers/testset_router.py
- agenta-backend/agenta_backend/routers/user_profile.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/db_manager.py
- agenta-backend/agenta_backend/services/evaluation_service.py
- agenta-backend/agenta_backend/services/event_db_manager.py
> Minor Refactoring

- agenta-backend/agenta_backend/models/api/evaluation_model.py
- agenta-backend/agenta_backend/models/db_engine.py
- agenta-backend/agenta_backend/models/db_models.py
- agenta-backend/agenta_backend/services/container_manager.py
It turns out that the evaluation prompt template isn't being saved to the evaluation document. I've added a new field to the db and API model and have tested it.
Dependency of #390
> Enhancement - evaluation prompt template field addition

- agenta-backend/agenta_backend/models/api/evaluation_model.py
- agenta-backend/agenta_backend/models/db_models.py
This PR adds optional fields for saving the AI critique evaluation prompt.
> Update - added evaluation prompt template

- agenta-cli/README.md
- agenta-cli/agenta/cli/variant_commands.py
- docs/installation/local-installation/local-installation.mdx
- docs/quickstart/getting-started-code.mdx
- docs/tutorials/a-more-complicated-tutorial-draft.mdx
- docs/tutorials/first-app-with-langchain.mdx
It seems we have a bug for which http://localhost:3000 is not working (@bekossy can you please look into it).
Until then I removed the port 3000 from the docs.
> Removed port 3000 docs

- README.md
**Description:**
- Fix missing pointer `.`
- Fix missing colon `:`
- Fix bold text
> Done some grammatical-enhancement in README.md

- agenta-web/src/components/EvaluationTable/AICritiqueEvaluationTable.tsx
- agenta-web/src/lib/Types.ts
> [bug] AI Critic prompt is not saved after evaluation is finished

- agenta-web/cypress/e2e/app-navigation.cy.ts
- agenta-web/cypress/support/commands/evaluations.ts
- agenta-web/cypress/support/commands/index.ts
Refactored test setup to create a variant and utilize its ID for consistent testing.
> Cypress fix: App Navigation

- docs/quickstart/getting-started-ui.mdx
Changed Add **you** API keys to Add **your** API keys
Incorrect grammar
> Spelling fix: Update getting-started-ui.mdx

- CODE_OF_CONDUCT.md
Quite an interesting project, was reading it and fixed some typos while doing so.
I'm happy to contribute to this project.
> Updated language of CODE_OF_CONDUCT.md

- agenta-web/cypress.config.ts
- agenta-web/package-lock.json
- agenta-web/package.json
- read cypress key from env
related to #796
> Read cypress key from env

- README.md
There are some grammatical errors in readme file. This PR fixes these errors.
> fixed grammatical error in README.md

- agenta-cli/agenta/cli/helper.py
When merged, this PR resolves #840
> Resolve Bug with Api Key Configuration

- agenta-web/src/components/Sidebar/Sidebar.tsx
This pull request addresses several issues affecting the user interface when the sidebar is collapsed. It includes 
- Fixes for tooltip clashes between the Menu Item title and the Tooltip title
- Hiding the Username when the sidebar is collapsed
- Ensures compatibility with Chrome and Firefox browsers.
Issue [#139](https://github.com/Agenta-AI/agenta_ee/issues/139)
> Fix collapsible sidebar in ee

- agenta-backend/agenta_backend/services/templates_manager.py
The code did not work if the image in the repo where different from the ones in the json. Now the json is the ground truth
> improvements

- agenta-backend/agenta_backend/services/db_manager.py
> Refactored Get User

- agenta-web/src/components/Layout/Layout.tsx
Issue [#149](https://github.com/Agenta-AI/agenta_ee/issues/149)
> Integrate Intercom with agenta cloud

- agenta-backend/agenta_backend/services/container_manager.py
- agenta-cli/agenta/templates/extract_data_to_json/app.py
- examples/baby_name_generator/app.py
- examples/chat_models/app.py
- examples/completion_models/app.py
- examples/extract_data_to_json/app.py
> Openai migration after depracation

- .github/workflows/docker.yml
- agenta-web/prod.gh.Dockerfile
- docker-compose.gh.yml
> Installation_agenta

- agenta-backend/agenta_backend/__init__.py
- agenta-backend/agenta_backend/main.py
- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/routers/bases_router.py
- agenta-backend/agenta_backend/routers/configs_router.py
- agenta-backend/agenta_backend/routers/container_router.py
- agenta-backend/agenta_backend/routers/environment_router.py
- agenta-backend/agenta_backend/routers/evaluation_router.py
- agenta-backend/agenta_backend/routers/observability_router.py
- agenta-backend/agenta_backend/routers/organization_router.py
- agenta-backend/agenta_backend/routers/testset_router.py
- agenta-backend/agenta_backend/routers/user_profile.py
- agenta-backend/agenta_backend/routers/variants_router.py
- agenta-backend/agenta_backend/services/app_manager.py
This PR syncs renaming refactoring to the cloud in the open-source version.
> Sync refactoring - files renamed from ee to cloud

- agenta-backend/agenta_backend/__init__.py
- agenta-backend/agenta_backend/main.py
- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/routers/bases_router.py
- agenta-backend/agenta_backend/routers/configs_router.py
- agenta-backend/agenta_backend/routers/container_router.py
- agenta-backend/agenta_backend/routers/environment_router.py
- agenta-backend/agenta_backend/routers/evaluation_router.py
- agenta-backend/agenta_backend/routers/observability_router.py
- agenta-backend/agenta_backend/routers/organization_router.py
- agenta-backend/agenta_backend/routers/testset_router.py
- agenta-backend/agenta_backend/routers/user_profile.py
- agenta-backend/agenta_backend/routers/variants_router.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/db_manager.py
- agenta-backend/agenta_backend/services/deployment_manager.py
- agenta-web/cypress/support/commands/utils.ts
- agenta-web/src/lib/helpers/utils.ts
This PR removes the 'demo' feature flag from the oss codebase.
Closes #899
> Refactor - remove 'demo' ff from codebase

- agenta-web/src/components/AppSelector/modals/CreateAppStatusModal.tsx
- agenta-web/src/components/Evaluations/AutomaticEvaluationResult.tsx
- agenta-web/src/components/Evaluations/HumanEvaluationResult.tsx
- agenta-web/src/components/TestSetTable/TestsetTable.tsx
Issue [#156](https://github.com/Agenta-AI/agenta_cloud/issues/156)
> Make some components' content invisible in Posthog - oss

- agenta-web/src/lib/helpers/evaluate.ts
PR For issue #916 
I looked at other PRs, there didn't seem to be a specific format for writing PR.
if there is, feel free to give us feedback. Always welcome 👏
> FIX #916 :  change the field name of 'ai critique' referring field

- agenta-web/src/components/EvaluationTable/AICritiqueEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/CustomCodeRunEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/ExactMatchEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/RegexEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/WebhookEvaluationTable.tsx
- agenta-web/src/lib/helpers/evaluate.ts
- agenta-web/src/lib/helpers/testset.ts
fixed export csv issue for auto evaluations in chat mode
> Fix: Export CSV for Auto Evaluations

- agenta-web/src/components/AppSelector/modals/AddAppFromTemplateModal.tsx
- agenta-web/src/components/AppSelector/modals/CreateAppStatusModal.tsx
> Remove not needed space

- .github/workflows/check-python-code-black.yml
- .github/workflows/check-web-code-lint-and-build.yml
- .github/workflows/check-web-code-prettier.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/push-to-ghcr.yml
- .github/workflows/run-backend-tests.yml
- .github/workflows/run-frontend-tests.yml
better names to gihub workflows
add workflow_dispatch to push to ghcr
> improve workflows

- agenta-backend/agenta_backend/models/converters.py
Resolve #981 
This is trivial update.
So much the better if there is better solution 😄
> BUG FIX #981: update 'parameter' of app to use 'config.parameters'

- agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
- agenta-web/src/components/Evaluations/EvaluationCardView/EvaluationInputs.tsx
Issue [#189](https://github.com/Agenta-AI/agenta_cloud/issues/189)
> Improve Human evaluation views

- agenta-web/src/components/Playground/AddToTestSetDrawer/AddToTestSetDrawer.tsx
> #1009 | Feature: All turns of a chat to testset

- agenta-backend/agenta_backend/routers/evaluation_router.py
This codemod replaces all instances of functions in the random module (e.g. random.random() with their, much more secure, equivalents from the secrets module (e.g. secrets.SystemRandom().random()).
There is significant algorithmic complexity in getting computers to generate genuinely unguessable random bits. The random.random() function uses a method of pseudo-random number generation that unfortunately emits fairly predictable numbers.
If the numbers it emits are predictable, then it's obviously not safe to use in cryptographic operations, file name creation, token construction, password generation, and anything else that's related to security. In fact, it may affect security even if it's not directly obvious.
Switching to a more secure version is simple and the changes look something …
> Secure Source of Randomness

- agenta-web/package-lock.json
- agenta-web/package.json
This pull request updates the posthog-js version from 1.87.2 to 1.94.4. The new version includes bug fixes and improvements. This update ensures that our application is using the latest version of posthog-js, which provides better performance and stability.
> Update posthog-js version to 1.94.4

- docs/self-host/host-locally.mdx
This pull request includes the following changes:
- Updated the layout of the user profile page to improve readability and user experience.
- Added a new section for displaying user statistics and achievements.
- Refactored the code to improve maintainability and performance.
These changes were made to enhance the user profile page and provide a better overall user experience.
> Update user profile page layout

- agenta-cli/pyproject.toml
This pull request updates the agenta version from 0.6.4 to 0.6.5. The new version includes bug fixes and improvements to the LLMOps platform. This update ensures that the SDK is up to date and provides a better experience for users.
> Update agenta version to 0.6.5

- docs/cookbook/extract_job_information.mdx
- docs/cookbook/list_templates_by_architecture.mdx
- docs/cookbook/list_templates_by_technology.mdx
- docs/cookbook/list_templates_by_use_case.mdx
- docs/mint.json
- docs/sdk/config_datatypes.mdx
This pull request adds job extraction templates and tutorials to the repository. The templates include extraction using OpenAI Functions and Langchain, and are indexed by architecture, technology, and use case.
> Add job extraction templates and tutorials

- examples/baby_name_generator/app_async.py
- examples/job_info_extractor/README.md
- examples/job_info_extractor/app.py
This pull request adds an async version of the baby name generator app. It includes the necessary changes to the code to make it compatible with asynchronous operations.
> Add async version of baby name generator app

- agenta-backend/agenta_backend/services/docker_utils.py
- docker-compose.gh.yml
- docker-compose.prod.yml
- docker-compose.yml
Related to https://github.com/Agenta-AI/agenta/issues/1095
> fix: setting docker to always restart for both base-containers and apps

- docs/tutorials/build-rag-application.mdx
This pull request updates the tutorial by adding a link to the full code for the tutorial. The link directs to the GitHub repository where the code can be found.
> Update tutorial with link to full code

- agenta-backend/agenta_backend/main.py
Corrected the app lifespan I had previously commented out during development.
> fix app lifespan

- README.md
- displays the total score and votes
- clickable to directly rate the repo on RepoRater
https://repo-rater.eddiehub.io
> RepoRater badge

- docker-compose.gh.yml
- docker-compose.prod.yml
- docker-compose.yml
This PR resolves the issue of communication between the backend service and the host machine.
> Update - added extra host to backend service in compose

- agenta-web/src/components/AppSelector/AppSelector.tsx
> Enhance app name validation

- agenta-web/src/lib/helpers/utils.ts
This pull request refactors the variable renaming logic in the utils.ts file. Specifically, it updates the renameVariables function to handle the "inputs" variable separately and renames it to "Prompt Variables". Many users were confused with the naming inputs.
> Refactor variable renaming in utils.ts

- agenta-web/src/components/ChatInputs/ChatInputs.tsx
- agenta-web/src/components/Playground/Views/TestView.tsx
> Enhance error message clarify in playground

- examples/async_startup_technical_ideas/app.py
- examples/baby_name_generator/app.py
- examples/baby_name_generator/app_async.py
- examples/chat_json_format/app.py
- examples/chat_models/app.py
- examples/extract_data_to_json/app.py
- examples/startup_technical_ideas/app.py
- examples/vision_gpt_explain_image/app.py
This PR includes modifications to display additional information (cost, latency, usage tokens) in the response for the example templates.
Resolves fourth task in #988 and closes #1061.
Requires #988 to be completed ⚠️
> Enhancement - improve LLM app templates response

- agenta-web/src/components/Playground/Views/TestView.tsx
> [Bug]: Error when trying to Load testset in playground

- README.md
- agenta-cli/README.md
- agenta-web/src/components/AppSelector/modals/WriteOwnAppModal.tsx
- docs/cookbook/list_templates.mdx
- docs/cookbook/list_templates_by_technology.mdx
- docs/cookbook/list_templates_by_use_case.mdx
- docs/depractated/learn/llm_app_architectures.mdx
- docs/depractated/learn/the_llmops_workflow.mdx
- docs/depractated/quickstart/getting-started-code.mdx
- docs/depractated/quickstart/how-agenta-works.mdx
- docs/depractated/quickstart/installation.mdx
- docs/developer_guides/cli/install.mdx
- docs/developer_guides/contributing/getting-started.mdx
- docs/getting_started/getting-started-ui.mdx
- docs/getting_started/introduction.mdx
- docs/mint.json
- docs/self-host/host-locally.mdx
> fix broken links

- agenta-web/src/hooks/useBlockNavigation.ts
> Refreshing playground and testset results in an alert

- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/Playground/Playground.tsx
- agenta-web/src/components/ResultComponent/ResultComponent.tsx
- agenta-web/src/pages/apps/[app_id]/endpoints/index.tsx
- agenta-web/src/pages/apps/[app_id]/testsets/new/upload/index.tsx
> Loading variants not visible in dark mode

- agenta-web/src/components/pages/evaluations/evaluationResults/NewEvaluationModal.tsx
> [BUG]: Rate limit config validation

- agenta-web/src/components/AppSelector/AppCard.tsx
- agenta-web/src/components/AppSelector/AppSelector.tsx
> Update styles in AppCard and AppSelector components

- agenta-backend/agenta_backend/routers/variants_router.py
- agenta-web/src/components/AppSelector/AppSelector.tsx
This pull request fixes the environment variable injection in the variant router and adds a lodash import and an update to the providerKey condition in the AppSelector component.
> Fix environment variable injection to enable cloud user to use their own keys

- agenta-backend/agenta_backend/migrations/23_01_prompt_versioning/20240123133518_updating_app_variant.py
- agenta-backend/agenta_backend/migrations/23_01_prompt_versioning/20240123133544_create_app_variant_revision.py
- agenta-backend/agenta_backend/migrations/23_01_prompt_versioning/20240123133603_updating_app_environment.py
- agenta-backend/agenta_backend/migrations/23_01_prompt_versioning/20240124110202_connection_evaluation.py
- agenta-backend/agenta_backend/models/api/evaluation_model.py
- agenta-backend/agenta_backend/models/converters.py
- agenta-backend/agenta_backend/models/db_models.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/evaluation_service.py
- agenta-backend/agenta_backend/tests/conftest.py
- agenta-backend/agenta_backend/tests/variants_main_router/conftest.py
- agenta-backend/agenta_backend/tests/variants_main_router/test_app_variant_router.py
- agenta-backend/agenta_backend/tests/variants_main_router/test_observability_router.py
- agenta-backend/agenta_backend/tests/variants_main_router/test_variant_evaluators_router.py
- agenta-web/src/lib/Types.ts
This PR includes:
- Migration for prompt versioning
- Refactoring of fixtures and testcases
- Fix for variant update issue (this error occurs in the prompt versioning branch)
> Enhancement: prompt versioning refacotr & migration

- agenta-web/src/components/Sidebar/Sidebar.tsx
> Saved sidebar collaspe state in localStorage

- agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240112120721_evaluation_scenarios_revamp.py
- agenta-backend/agenta_backend/models/converters.py
- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/tasks/evaluations.py
- agenta-cli/agenta/sdk/agenta_decorator.py
- agenta-cli/pyproject.toml
The LLM app container now raises the appropriate status code for a raised exception. When I injected an incorrect OPENAI API key, I received a 401 status code along with the exception message.
Closes #1283
> Update - modified agenta sdk handle_exception

- agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240112120721_evaluation_scenarios_revamp.py
- agenta-backend/agenta_backend/models/api/evaluation_model.py
- agenta-backend/agenta_backend/models/converters.py
- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/evaluators_service.py
- agenta-backend/agenta_backend/tasks/evaluations.py
- agenta-backend/agenta_backend/tests/variants_main_router/test_variant_evaluators_router.py
- agenta-cli/agenta/sdk/agenta_decorator.py
- agenta-web/src/components/AppSelector/AppSelector.tsx
- agenta-web/src/components/Evaluations/Evaluations.tsx
- agenta-web/src/components/pages/evaluations/evaluationResults/NewEvaluationModal.tsx
- agenta-web/src/lib/Types.ts
- agenta-web/src/lib/helpers/utils.ts
- agenta-web/src/lib/services/api.ts
```
lm_providers_keys: apiKeyObject(),
```
apiKeyObject would return an object of the provided api keys 
`
{
[API KEY NAME]_API_KEY: "sk-xxx"
}
`
> Fix logic for sending API key in FE

- agenta-web/src/lib/helpers/evaluate.ts
Fixed eval table sorting and added '-' for missing results
> Fix: Evaluation table sorting

- agenta-web/src/components/Evaluations/EvaluationCardView/index.tsx
> Implement State-Persistence for Human Evaluation

- agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
> FIX: Evaluation scenario results are not exported correctly

- agenta-cli/agenta/docker/docker-assets/Dockerfile.template
- agenta-cli/agenta/docker/docker-assets/main.py
- agenta-cli/pyproject.toml
This PR resolves the issue of the llm app openapi.json not being reachable.
The agenta-cli version has been bumped to 0.10.3
> Bug Fix: Update dockerfile.template in agenta-cli

- agenta-backend/agenta_backend/services/llm_apps_service.py
- agenta-backend/agenta_backend/tasks/evaluations.py
- docker-compose.test.yml
This pull request adds an assertion for when the app variant is not found.
> Add assertion for app variant not found

- agenta-web/src/components/AppSelector/AppSelector.tsx
> Update - Make + Create New App aligned with dark mode

- agenta-web/cypress/e2e/eval.comparison.cy.ts
- agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx
> Add a cursor when hovering over an evaluation result cell

- agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
> Columns becomes very small in comparison view

- agenta-web/src/components/pages/evaluations/evaluators/NewEvaluatorModal.tsx
> Add evaluator name in the "Configure your evaluator" modal

- agenta-web/src/components/pages/evaluations/evaluators/NewEvaluatorModal.tsx
> Increased code evaluation modal width

- agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx
> Removed cell redirect on variant and testset

- agenta-web/src/components/Evaluations/EvaluationCardView/index.tsx
> Improve card view in Human Evaluation

- agenta-web/src/components/pages/evaluations/cellRenderers/cellRenderers.tsx
- agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
- agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
> We can't see the full output value in evaluations scenarios

- agenta-web/src/lib/Types.ts
Corrected parameters types in deployment view
Issue #1401
> Sub Fix to Issue 1401: Corrected parameters type

- agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx
> Add button to filter evaluators column in Evaluation results view

- agenta-web/src/components/Playground/AddToTestSetDrawer/AddToTestSetDrawer.tsx
> Allow the addition of a data point from the playground when columns mismatch

- agenta-web/src/components/Playground/Views/ParametersView.tsx
- agenta-web/src/components/Playground/Views/TestView.tsx
- agenta-web/src/lib/Types.ts
- agenta-web/src/lib/hooks/useVariant.ts
- agenta-web/src/lib/services/api.ts
Issue [#29](https://github.com/Agenta-AI/agenta-commons/issues/29)
> Removed commons related types and apis in oss

- agenta-web/src/components/pages/evaluations/cellRenderers/cellRenderers.tsx
- agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx
- agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
> All rows are collapsed after switching off "Show diff"

- agenta-web/src/components/AppSelector/AppSelector.tsx
> Pressing the enter key should equal creating an application

- agenta-web/src/lib/helpers/openapi_parser.ts
> [Bug Fix]: Playground sidebar parameters have wrong min and max values

- agenta-cli/agenta/cli/helper.py
See discussion in slack https://agenta-hq.slack.com/archives/C05JDQWKD6E/p1713366491440119
> strip api key in cli when added with a new line

- agenta-web/src/components/Playground/Views/TestView.tsx
- agenta-web/src/lib/helpers/formatters.ts
> [Bug Fix]: Fixed latency format in evaluation view

- agenta-backend/agenta_backend/services/templates_manager.py
> Increased time out to 90s for fetching from docker hub

- agenta-backend/agenta_backend/models/db_models.py
- agenta-backend/agenta_backend/services/db_manager.py
This PR resolves the wrong timestamp in variant configuration. See below:
Closes #1537
> [Bug Fix]: wrong timestamp in configuration

- agenta-web/src/components/Playground/Views/TestView.tsx
> [Bug Fix]: Chat template returns error body in case of empty input

- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/routers/variants_router.py
- agenta-backend/agenta_backend/services/app_manager.py
This PR publishes the first variant created through the user interface and command-line interface to the production environment by default.
Closes #1585
> [Enhancement] publish the first variant to the production environment per default

- agenta-web/src/code_snippets/endpoints/fetch_config/python.ts
> Fixed fetch config Python code snippet

- agenta-web/src/components/Playground/ViewNavigation.tsx
- agenta-web/src/components/ResultComponent/ResultComponent.tsx
> Remove Loading icon in Result component

- agenta-backend/agenta_backend/services/llm_apps_service.py
> [Hotfix] Increased timeout for invoking evaluation

- agenta-backend/agenta_backend/services/evaluator_manager.py
- agenta-web/src/components/pages/evaluations/evaluators/AdvancedSettings.tsx
- agenta-web/src/components/pages/evaluations/evaluators/NewEvaluatorModal.tsx
@bekossy can you check the scenario when we update the correct_answer
> advanced settings in a separate component

- agenta-web/src/lib/helpers/dateTimeHelper.ts
> [Bug Fix]: The testsets UI is dropping the trailing 0 from the timestamp

- .better-commits.json
The new scope is app, frontend, backend, sdk, cli
> chore: Improved scope for better commit

- agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
> [Bug]: Redirect Issue When Deleting Evaluation in Evaluation Results View

- agenta-web/src/pages/apps/[app_id]/testsets/new/api/index.tsx
Refactored the testset-new-api page import paths for better readability.
> Refactor: improved the testset new api page import path

- agenta-backend/agenta_backend/models/converters.py
fix the access to variant revision for deleted variants
Closes: 1817
> fix(backend): 1817 fix access to variant revision

- agenta-backend/agenta_backend/services/results_service.py
Closes [AGE-360](https://linear.app/agenta/issue/AGE-360/score-calculation-for-human-single-modal-differs-in-view)
See issue for context.
> fix(backend): Score Calculation for Human Single Modal differs in view

- cookbook/creating_evaluators_with_sdk.ipynb
> docs(tool): AGE-367 added new cookbook

- docs/guides/evaluation_from_sdk.mdx
- docs/mint.json
> docs(tool): AGE-367 add doc for using sdk

- agenta-backend/agenta_backend/models/api/api_models.py
- agenta-backend/agenta_backend/models/converters.py
- agenta-backend/agenta_backend/models/db_engine.py
- agenta-backend/agenta_backend/models/db_models.py
- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/routers/configs_router.py
- agenta-backend/agenta_backend/routers/evaluation_router.py
- agenta-backend/agenta_backend/routers/evaluators_router.py
- agenta-backend/agenta_backend/routers/human_evaluation_router.py
- agenta-backend/agenta_backend/routers/testset_router.py
- agenta-backend/agenta_backend/routers/variants_router.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/db_manager.py
- agenta-backend/agenta_backend/services/deployment_manager.py
- agenta-backend/agenta_backend/services/evaluator_manager.py
- agenta-backend/agenta_backend/services/user_service.py
- agenta-backend/agenta_backend/tasks/evaluations.py
This PR migrates beanie related code for cloud/ee to sqlalchemy-orm.
> [cloud related] migration/beanie to sqlalchemy

- agenta-backend/agenta_backend/services/db_manager.py
This PR addresses the need for backward compatibility in the user lookup logic after API key migration.
> Enhancement: update user lookup logic for backward compatibility in api key migration

- README.md
- docs/mint.json
- docs/self-host/migration/migration-to-mongodb.mdx
- docs/self-host/migration/migration-to-postgres.mdx
> AGE-386 Updated documenation and Readme for migration

- agenta-backend/agenta_backend/migrations/mongo_to_postgres/README.md
- agenta-backend/agenta_backend/migrations/mongo_to_postgres/docker-compose.migration.yml
- docker-compose.gh.yml
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
- docs/self-host/migration/migration-to-postgres.mdx
- Add dedicated docker compose for migration
- remove mongo from all docker composes
- Updating migration docs
> docker compose cleanup from mongo post-migration

- agenta-web/package-lock.json
- agenta-web/package.json
**Description:**
Updated the `@sentry/nextjs` package to fix the `TypeError: request.headers.split is not a function` error.
> Fix: outdated sentry version 

- start_web_standalone.sh
You can now use ./start_web_standalone.sh dockerfile and it would start nexjs outside of  docker
> feat(app): startweb standalone on any docker

- agenta-backend/agenta_backend/routers/app_router.py
[description unavailable due to issue's security concerns]
> [Bug Fix]: age-374

- agenta-backend/agenta_backend/routers/configs_router.py
- agenta-backend/agenta_backend/services/db_manager.py
This PR adds backward compatibility for LLM apps that are still using Mongoid as their config/base ID.
Closes [AGE-409](https://linear.app/agenta/issue/AGE-409/[bug]-uuid-issue-in-production)
> [Bug Fix]: resolve get_config exception: badly formed hexadecimal UUID string

- agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx
- agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
- agenta-web/src/components/Playground/ViewNavigation.tsx
- agenta-web/src/components/Playground/Views/TestView.tsx
- agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
- agenta-web/src/lib/Types.ts
- agenta-web/src/lib/helpers/playgroundResp.ts
- agenta-web/src/services/api.ts
- agenta-web/src/services/baseResponseMock.json
This PR displays inline intermediate outputs
Closes [AGE-457](https://linear.app/agenta/issue/AGE-457/[poc-1]-display-optional-inline-intermediate-outputs-in-playground)
TODO
- Code cleanup
> [PoC-1] Display optional inline intermediate outputs in Playground

- agenta-web/src/components/Playground/ParamsForm/ParamsForm.tsx
- agenta-web/src/components/Playground/PlaygroundDrawer/PlaygroundDrawer.tsx
- agenta-web/src/components/Playground/PlaygroundDrawer/tabItems.tsx
This Pull Request fixes and improves the User interface in the rag branch
This PR closes the following issue:
> [PoC-1][Frontend]: UI fixes

- agenta-backend/agenta_backend/main.py
- agenta-backend/agenta_backend/migrations/postgres/utils.py
- docker-compose.gh.yml
- docker-compose.prod.yml
- docker-compose.test.yml
- docker-compose.yml
This PR simply add a feature-flag to handle MongoDB initialization for cloud and also update the imports required to check new migration in cloud.
> [Enhancement]: Add cloud support for alembic

- agenta-web/cypress/e2e/single-model-test-evaluation.cy.ts
- agenta-web/src/components/Evaluations/AutomaticEvaluationResult.tsx
**Description:**
Added test for modifying the single model evaluation scores.
**Changes:**
- Added test for modifying the single model scores.
- `cy.wait(1000)`  waits are for loading the data properly.
> Test: modify single model evaluation scores

- agenta-backend/agenta_backend/resources/evaluators/evaluators.py
Very minor. The previous description of the evaluator was wrong and confusing (a user was asking about it today)
> fix(backend): fix json evaluator description

- agenta-backend/agenta_backend/models/api/api_models.py
- agenta-backend/agenta_backend/models/converters.py
- agenta-backend/agenta_backend/services/db_manager.py
- agenta-cli/agenta/client/backend/types/app_variant_response.py
This PR adds modification tracking for variants by introducing a `ModifiedBy` model. It also optimizes 3 DB functions with `joinedload` to reduce query count and improve performance.
1. Create an app from the UI and navigate to the playground.
2. Create an app from the CLI and navigate to the playground.
If both apps load correctly in the playground, the endpoint is functioning as expected and returning the modification information for all variants. If either app fails to load or shows errors, it indicates an issue that should be reported.
> [Enhancement]: added modification information for variant

- examples/chat_models/app.py
- examples/chat_models/requirements.txt
Closes: AGE-612
In the new version of langchain some of the dependencies are withing langchain_community package. This resolves this issue
> fix(tool): AGE-612 fix dependencies with langchain_community

- agenta-backend/agenta_backend/models/api/api_models.py
- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/services/db_manager.py
- agenta-backend/agenta_backend/tests/variants_main_router/test_app_variant_router.py
This PR introduces an endpoint to update an existing app, including the necessary backend logic and test cases.
Closes [AGE-539](https://linear.app/agenta/issue/AGE-539/endpoint-for-renaming-an-application)
- Added a new `update_app` router to handle app update requests.
- Implemented the `update_app` DB function to update app details in the database.
- Added test cases to validate the update functionality.
- **App Update via API:**  
- Test the new update endpoint by updating an app’s details (e.g., name) and verify that the changes are correctly reflected in the database.
- **Error Handling:**  
- Test edge cases like updating non-existent apps or providing invalid data and verify that appropriate errors are returned.
1. **Create App:**
- Create an app from the UI or CLI
2. **Update App …
> [Enhancement]: Implemented endpoint for renaming an application

- agenta-web/src/components/AppSelector/AppCard.tsx
- agenta-web/src/components/AppSelector/modals/EditAppModal.tsx
- agenta-web/src/pages/apps/[app_id]/overview/index.tsx
- agenta-web/src/services/app-selector/api/index.ts
Closes [AGE-633](https://linear.app/agenta/issue/AGE-633/[frontend]-implement-feature-to-rename-app)
> feat(frontend): Implement Feature to Rename App

- .github/workflows/bump-versions.yml
The enhancement will include the version name in the branch name and the PR name
example:
https://github.com/Agenta-AI/agenta/pull/2020
> Bump version enhancement

- .github/workflows/check-python-code-black.yml
- website/scripts/generate_cookbooks.py
> add linting for website scripts

- website/docusaurus.config.ts
- website/package-lock.json
- website/package.json
- website/src/css/custom.css
Added Posthog plugin to track user's activity in documentation.
- Added Posthog plugin.
- Fixed the large screen size issue.
> Doc: added posthog for tracking

- website/docusaurus.config.ts
Fixed the Posthog connectivity issue.
> Doc: fixed posthog connectivity

- website/docs/evaluation/test_sets.mdx
- website/docs/observability/quickstart.mdx
- website/docs/prompt_management/integrating.mdx
- website/docs/reference/cli/core_commands/init.mdx
- website/docs/reference/cli/core_commands/variant_list.mdx
- website/docs/reference/cli/core_commands/variant_remove.mdx
- website/docs/reference/cli/core_commands/variant_serve.mdx
Fixed the heading wrong placement issue in several places within the doc.
> Doc: fixed heading wrong placement

- agenta-backend/agenta_backend/models/converters.py
- agenta-backend/agenta_backend/resources/evaluators/evaluators.py
- agenta-backend/agenta_backend/services/llm_apps_service.py
This PR fixes all the bugs reported after the full QA for the v24.04.0 release.
- [Commons_pr110](https://github.com/Agenta-AI/agenta-commons/pull/110)
- https://linear.app/agenta/issue/AGE-952/clicking-on-any-deployments-results-in-an-error
- https://linear.app/agenta/issue/AGE-955/unable-to-see-production-deployment-history
- https://linear.app/agenta/issue/AGE-957/unable-to-remove-project-member
- https://linear.app/agenta/issue/AGE-953/bug-when-running-evaluation-unsupported-operand
> Fix Bugs for v0.25.0 Release

- agenta-web/src/components/Sidebar/Sidebar.tsx
This PR aims to fix the padding issue in the workspace selector component.
Closes [AGE-629](https://linear.app/agenta/issue/AGE-634/padding-issues-on-left-side-of-workspace-select)
> fix(frontend): padding issue in workspace selector component

- agenta-backend/agenta_backend/services/security/sandbox.py
This PR improves the custom code evaluation sandbox to remove the restriction limiting the output range to 0 and 1. Additionally, it improves the error handling with detailed exception messages. 
- Updated `execute_code_safely` function to accept results that are integers or strings if they can be cast to floats.
- Removed the restriction limiting the output range to 0 and 1, allowing more flexibility in the function's return values.
- Improved error handling with detailed exception messages for:
- Type conversion errors when converting results to float.
- Syntax errors in the provided code.
- Key errors for missing expected keys in the environment.
- Generic runtime errors during execution.
> [Enhancement]: Improve custom code evaluation sandbox 

- agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
- agenta-web/src/pages/apps/[app_id]/observability/index.tsx
Closes [AGE-1181](https://linear.app/agenta/issue/AGE-1181/traces-with-on-single-main-span-are-not-correctly-rendered)
> (frontend)[Age 1181]: Traces with on single main span are not correctly rendered

- docs/docs/getting-started/02-quick-start.mdx
Minor change to the documentation. Created new video quick start guide and updated it
> Updated video quick start tutorial

- agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
This PR aims to fix the search filter issue due to a change in the data property where it gets replaced by content property.
> fix(frontend): replaced data property with content for search filter

- .github/dependabot.yml
- Added other projects not covered by Dependabot
> Adjust dependabot config file

- agenta-web/src/components/Filters/Filters.tsx
This PR aims to fix the observability filter apply and clear functions logic to prevent unnecessary API calls.
> fix(frontend): observability filter apply and clear conditions

- docs/docs/prompt-management/integration/02-fetch-prompts.mdx
> AGE-1359 Minor fix to fetch prompt docs

- agenta-web/src/code_snippets/endpoints/fetch_config/curl.ts
- agenta-web/src/code_snippets/endpoints/fetch_config/python.ts
- agenta-web/src/code_snippets/endpoints/fetch_config/typescript.ts
- agenta-web/src/components/pages/overview/deployments/DeploymentDrawer.tsx
This PR aims to fix the prompt fetching code by replacing the old code with the new code.
Closes [AGE-1332](https://linear.app/agenta/issue/AGE-1332/change-the-prompt-fetching-code-in-the-ui#comment-3eefa54e)
> fix(frontend): prompt fetching code

- docs/docs/reference/api/fetch-evaluation-ids-evaluations-by-resource-get.api.mdx
A previous [PR](https://github.com/Agenta-AI/agenta/commit/7fcc849495dbed8913f13068af6642b2d06db030#diff-7e22548aea35930072cc3e3be90cfb77dbf43dae34c7bc407710bbfbeffd3f9a) introduced an issue in the docs build. This PR fixed it.
> Fix to the docs build

- .github/workflows/check-web-code-prettier.yml
- agenta-web/src/hooks/useAppId.ts
set prettier version in the prettier workflow
> set prettier version

- agenta-backend/pyproject.toml
- agenta-web/package.json
> sync versions

- agenta-web/package.json
- Added a new command to run dev locally outside of containers
`npm run dev:turbo`
- Please make sure to `npm install next@rc` locally first
> NextJS turbo in dev mode

- agenta-web/src/lib/helpers/fileManipulations.ts
Closes [AGE-1396](https://linear.app/agenta/issue/AGE-1396/[bug]-upload-testset-from-csv-validation-failing)
> (frontend)[AGE-1396]: Upload testset from CSV validation failing

- agenta-web/src/components/Sidebar/Sidebar.tsx
Closes [AGE-1469](https://linear.app/agenta/issue/AGE-1469/[ui]-side-bar-spacing-is-wrong-in-small-screens)
> (frontend)[AGE-1469]: Side bar spacing is wrong in small screens

- agenta-backend/agenta_backend/migrations/postgres/versions/0f086ebc2f82_added_the_app_type_column_to_the_app_db_.py
- agenta-backend/agenta_backend/migrations/postgres/versions/0f086ebc2f83_extend_app_type.py
- agenta-backend/agenta_backend/models/api/api_models.py
- agenta-backend/agenta_backend/models/db_models.py
- agenta-backend/agenta_backend/models/shared_models.py
- agenta-backend/agenta_backend/routers/app_router.py
- agenta-backend/agenta_backend/services/app_manager.py
- agenta-backend/agenta_backend/services/db_manager.py
- Requires `SERVICE_URL_TEMPLATE`
> [feature] shared services - create variants from service key

- agenta-cli/agenta/sdk/types.py
Set the model config to None. Light QA'ed with the integration to the playground service and it works.
> fix(app): modified model config defaults to none

- agenta-web/src/components/pages/observability/components/AccordionTreePanel.tsx
- fixed editor scroll behavior via using proper options
- improved layout to prevent inner scrolling of wrapping collapse component
> Fix[AGE-1392] Improve editor scroll behavior in AccordionTreePanel

- agenta-backend/agenta_backend/services/llm_apps_service.py
- agenta-backend/agenta_backend/tasks/evaluations.py
- agenta-cli/agenta/sdk/middleware/auth.py
- agenta-cli/agenta/sdk/middleware/config.py
- agenta-cli/agenta/sdk/middleware/vault.py
This PR resolves broken observability in shared service, and also allowed unauthorized execution/requests when running OSS locally.
> [Bug Fix]: Broken Observability in Shared Services

- agenta-cli/agenta/sdk/middleware/auth.py
- added better exceptions handling and logging
Note: We should improve the logging class and create a centralized way to log and debug for SDK and backend (change env var->change debug behavior)
> refactor(sdk): improve errors in middleware auth

- agenta-web/src/components/Playground/index.tsx
- agenta-web/src/contexts/app.context.tsx
fixes [AGE-1517](https://linear.app/agenta/issue/AGE-1517/playground-root-component-fail-to-fetch-apps-of-an-org-a-user-is)
> [AGE 1517] Frontend: Fix apps fetching in playground root

- agenta-web/src/components/Playground/index.tsx
- agenta-web/src/contexts/app.context.tsx
> Revert "[AGE 1517] Frontend: Fix apps fetching in playground root"

- docs/docs/self-host/host-locally.mdx
> (docs) fix to self-hosting documentation

- web/oss/next.config.ts
> Hotfix self-hosting build by disabling typing

- hosting/docker-compose/oss/docker-compose.gh.yml
> Fix: Correct default variable syntax in docker-compose.gh.yml
