Agenta-AI/agenta

agenta-cli/agenta/cli/variant_commands.py, agenta-cli/agenta/docker/docker-assets/main.py, agenta-cli/agenta/docker/docker_utils.py, agenta-cli/pyproject.toml, docs/howto/creating-multiple-app-variants.mdx, docs/introduction.mdx, mint.json
Added option to enable creating a variant from a any file in the folder.
This allows users to create:
app1.py app2.py app3.py
in the same folder
then run
agenta variant serve --file_name app1.py
agenta variant serve --file_name app2.py
agenta variant serve --file_name app3.py
See documentation for more details
=> Fea  cli   file name to specify the file name with the code instead of running app.py

docs/tutorials/your-first-llm-app.mdx
Hello @mmabrouk, I made an error in the naming 😄. I confused `openai` with `openapi`.
=> Fix: renamed dep from openapi to openai

agenta-web/src/components/TestSetTable/InsertTestSetNameModal.tsx
Hi @mmabrouk,
This is an improvement of issue #111. I added a warning icon right before the content of the insert set name modal.
=> Added warning icon to modal content

agenta-web/src/components/Evaluations/Evaluations.tsx, agenta-web/src/components/Playground/LoadTestsModal.tsx, agenta-web/src/components/Playground/Views/TestView.tsx, agenta-web/src/lib/services/api.ts
What: 
https://github.com/Agenta-AI/agenta/issues/107
How: 
Create LoadTestsModal
Fetch test sets list on load of the modal using hook
add ways for users to replace existing test sets or add new items to existing test sets.
Result:
https://github.com/Agenta-AI/agenta/assets/8658374/768bf312-3518-48a6-9181-52421a58e47a
=> Load test sets in playgorund

agenta-web/src/components/Evaluations/Evaluations.tsx
Hi @mmabrouk ,
I've gotten rid of the error that says, Cannot use import statement outside a module. Merging this PR will close #146.
=> Fix "Cannot use import statement outside a module" Error

agenta-backend/agenta_backend/models/api/api_models.py, agenta-backend/agenta_backend/routers/container_router.py, agenta-backend/agenta_backend/services/container_manager.py, agenta-backend/agenta_backend/services/db_manager.py, agenta-web/src/components/AppSelector/AppSelector.tsx, agenta-web/src/components/CreateApp/AppTemplateCard.tsx, agenta-web/src/components/CreateApp/CreateApp.tsx, agenta-web/src/components/Sidebar/Sidebar.tsx, agenta-web/src/lib/Types.ts, agenta-web/src/lib/helpers/utils.ts, agenta-web/src/lib/services/api.ts, agenta-web/src/pages/apikeys.tsx
Integrated backend and frontend for starting with template option.
Closes #316
Please review the changes and provide feedback. Let me know if any further adjustments are needed.
=> Feat - Integration of be and fe for starting with template

agenta-backend/agenta_backend/routers/container_router.py, agenta-web/src/components/CreateApp/AppTemplateCard.tsx, agenta-web/src/components/CreateApp/CreateApp.tsx
When templates are unavailable due to an unknown architecture, an error message now informs users with clarity. The message reads: "No templates were found, this is a mistake. Please [fill an issue](https://github.com/Agenta-AI/agenta/issues/new)." This provides better feedback and guidance to users.
I've reorganized the API key logic to prioritize user experience. Now, before attempting to fetch and start an image, we first confirm the presence of an API key. If no key is found, a modal prompts users to navigate to the API key view. This enhances usability and reduces errors.
Please review and provide your insights on these enhancements. Thank you!
=> Ehancement - Add Error Message for Missing Templates and Reorder API Key Check

agenta-backend/agenta_backend/routers/app_variant.py, agenta-backend/agenta_backend/routers/container_router.py, agenta-web/src/lib/services/api.ts
This pull request addresses the task of refactoring the backend code to enhance code organization. The endpoint `/container/variants/create` has been relocated from the container router to the app_variant router.
=> Refactor - move /container/variants/create to app_variant router

docs/tutorials/your-first-llm-app.mdx
In the tutorial documentation, the temperature was not explicitly stated.
although there was a default value set in the code. 
I provided temperature and a little comment on what temperature does.
=> added temperature to the tutorial documentation

agenta-backend/agenta_backend/main.py, agenta-backend/agenta_backend/routers/container_router.py
This PR address the issue of starting a template from UI for being relatively slow. Setting up a logic to pull the container image(s) when the template for the container has been fetched from Docker Hub solved the issue.
Closes #423 
Please review and let me know if there are any improvements that I need to make. Thank you.
=> Enhancement - speed up starting a template from UI

agenta-web/prod.Dockerfile, docker-compose.prod.yml
In this PR, I have:
When merged, this PR closes #275 but is not yet ready to merge and I need help.
Although the prod.Dockerfile created is for building and starting next.js in Production, while testing locally I kept running into issues while running `npm run build` that I couldn't fix. 
first I ran into issues with js-beautify:
```
> [agenta_agenta-web 10/10] RUN npm run build:
#0 0.590 
#0 0.590 > dashboard@0.1.0 build
#0 0.590 > next build
#0 0.590 
#0 1.140 info  - Linting and checking validity of types...
#0 8.813 Failed to compile.
#0 8.813 
#0 8.813 ./src/code_snippets/endpoints/typescript.ts:1:30
#0 8.813 Type error: Could not find a declaration file for module 'js-beautify'. '/app/node_modules/js-beautify/js/index.js' implicitly has an 'any' type.
#0 8.813   Try `npm i …
```
=> feat: created and use production dockerfile for web

docs/howto/how-to-debug.mdx
When trying to access the apps page on the frontend, an error message appears saying "failed to load" due to an OperationError linked to the database, more specifically the absence of a column in a table. This PR addresses this issue by including a troubleshooting guide in the documentation.
=> Troubleshooting - Agenta web failing

.github/workflows/publish.yml
when merged, this PR closes #273 
I've worked on;
=> feat: publish w poetry on version change

.github/workflows/publish.yml
@mmabrouk Suspected issue for why this didn't work is the path limitation I set in the workflow which specifies that the workflow should only run when a push event happens on the main branch and the `pyproject.toml` was modified. 
I've now removed that and the workflow should run whenever main is updated.
=> update: remove path limitation

agenta-backend/agenta_backend/services/app_manager.py, agenta-backend/agenta_backend/services/db_manager.py
This PR gracefully handles variant deletion. Alongside this fix, I have also adjusted the logic to remove testsets for an app.
=> Fix - server crashing due to variant deletion not properly handled

.github/workflows/publish.yml
When Merged, this PR closes #549 and closes #501
This PR addresses the issue of the 'Publish agenta to PyPI" workflow failing if there's no version bump by continuing the workflow successfully if no version change is detected.
=> #549 poetry publish workflows failing when no version is bumped

agenta-backend/agenta_backend/routers/testset_router.py, agenta-web/src/pages/apps/[app_name]/testsets/index.tsx, agenta-web/src/pages/apps/[app_name]/testsets/new/endpoint/index.tsx
related to the issue #527
This PR adds a new method for creating a testset by importing data from an endpoint.
A new button has been added, leading to a new page where users can submit a testset name and endpoint. 
The server will fetch data from the endpoint and save it to the DB like what the `upload` method does. 
Currently I've only handled JSON format response.
I'm not a native English speaker, so if there are any English texts that need modification, please let me know.
Web screenshots:
=> #527 Import Testset from an Endpoint

.github/workflows/publish.yml
Status of [this](https://github.com/Agenta-AI/agenta/actions/runs/6102485188) shows the previous PR didn't fix it.
=> Fix poetry publish workflows failing when no version is bumped

agenta-web/src/components/Playground/NewVariantModal.tsx, agenta-web/src/components/Playground/VersionTabs.tsx
https://github.com/Agenta-AI/agenta/assets/128676129/2ce30d42-06b8-44fb-a418-27af4866f04a
=> bug/Disable the submit button when the variable name field is empty - #576

agenta-backend/agenta_backend/routers/app_variant.py, agenta-backend/agenta_backend/services/db_manager.py, agenta-backend/tests/test_router_app_variant.py, agenta-cli/agenta/client/client.py
This (Draft) PR addresses the API for fetching a specific app variant based on app_name and variant_name. The API parameters are passed as query parameters.
Related to Issue #571 
`GET /api/app_variant/get_variant_by_name/?app_name=test&variant_name=v1
`
**Unit Testing**: I still need to complete the `def test_get_variant_by_name()` function. Any suggestions on what parameters should be used for testing would be appreciated.
**Exception Handling**: Encountering an issue where the intended _404_ error is not being triggered as expected. Despite the condition `if app_variant is None` being met, a _500_ error is raised instead of a _404_ error. This happens when I remove the block `except HTTPException as e: raise`. Refer to [this line](https://github.com/yeokyeong-yanolja/agenta/blob/914e821 …
=> feature : develop Endpoint to Fetch LLM Application Variant Parameters

agenta-web/src/lib/services/api.ts
This PR resolves the following errors:
Mixed Content: The page at 'https://xxxxxxxx' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'https://xxxxxxxx'. This request has been blocked; the content must be served over HTTPS.
=> Fix - resolve mixed content issue error

agenta-web/src/components/Evaluations/Evaluations.tsx
I used a filter to check variants that are already selected and not display them. You can see a demo in this Loom: https://www.loom.com/share/cbd29524a821406782150e34bdee6cfa?sid=d3212da5-935b-48d0-8d21-831c5d159df2.
Closes #602
=> bugfix: prevent user from selecting the same variant twice

agenta-backend/agenta_backend/tests/conftest.py, agenta-backend/agenta_backend/tests/test_app_variant_router.py
When merged, this PR closes #666 
I have;
- Created fixtures to for getting a user object to use in tests.
- Created test for creating an app variant from template.
Tests keep failing with the error;
```
>       if payload.organization_id is None:
E       AttributeError: 'dict' object has no attribute 'organization_id'
agenta_backend/routers/app_variant.py:524: AttributeError
============================================================================== short test summary info ===============================================================================
FAILED agenta_backend/tests/test_app_variant_router.py::test_successfully_creates_new_app_variant - AttributeError: 'dict' object has no attribute 'organization_id'
```
=> sync Tests with new refactoring

agenta-web/src/components/Playground/Playground.tsx, agenta-web/src/components/Playground/ViewNavigation.tsx, agenta-web/src/components/Playground/Views/ParametersView.tsx, agenta-web/src/hooks/useBlockNavigation.ts, agenta-web/src/hooks/useQuery.ts
- warn for unsaved changes in variant
- playground refactoring
- bug fixes
Implementation Details:
We prompt users for unsaved changes as soon as they leave the variant tab. That includes not only leaving the playground page, but also switching to one variant from another within the playground. Also, variant tabs are now controlled by query params instead of the local React state, meaning that the playground URL now persists the selected variant tab.
=> 340 | Feature: Warn users when unsaved changes in payground variants

agenta-cli/agenta/cli/helper.py, agenta-cli/agenta/cli/main.py, agenta-cli/agenta/cli/variant_commands.py, agenta-cli/agenta/client/client.py
When merged, this PR resolves #738 
The following have been done;
I have tested that this addresses the target [issue](https://github.com/Agenta-AI/agenta/issues/738) and introduces no breaking changes or bugs.
=> Enable support for cloud hosted agenta in Agenta CLI

agenta-web/cypress/e2e/ai-critic-evaluation.cy.ts, agenta-web/cypress/e2e/regex-evaluation.cy.ts, agenta-web/cypress/support/commands/evaluations.ts
This pull request simplifies the Evaluation Workflow tests by extracting the testset name as a variable. This change ensures that the tests select the appropriate testset.
=> Update Evaluation Workflow tests

agenta-web/cypress/support/commands/evaluations.ts
Modified the test command to target the initial `create-app-button` attribute to resolve test failure caused by the appearance of two identical attributes when starting from the Template.
=> Evaluation command hot fix

agenta-cli/agenta/__init__.py, agenta-cli/agenta/sdk/__init__.py, agenta-cli/agenta/sdk/agenta_decorator.py, agenta-cli/agenta/sdk/types.py, examples/experimental/startup_feature_ideas/app.py, examples/experimental/startup_feature_ideas/requirements.txt
This PR introduces a new data type for messages within Agenta, allowing users to develop chat-based applications. 
Closes #869 
To make use of data type, kindly do the following:
```python
import agenta as ag
from agenta import MessagesInput
...
...
@ag.entrypoint
def chat(
inputs: MessagesInput = MessagesInput([{"role": "string", "content": "string"}])
) -> str:
pass
```
See experimental [application](https://github.com/Agenta-AI/agenta/blob/71a3e0a8336c0987ed3bc5254023c0f50bff0497/examples/experimental/startup_feature_ideas/app.py) for usage. Kindly review and identify any areas that may need improvement. Thank you!
=> Feat -  Implement Message Data Type for Chat-Based Applications

agenta-cli/agenta/cli/variant_commands.py, agenta-cli/agenta/docker/docker_utils.py
=> Cleanup files after serving

agenta-backend/agenta_backend/routers/app_router.py, agenta-backend/agenta_backend/routers/container_router.py, agenta-backend/agenta_backend/services/app_manager.py, agenta-backend/agenta_backend/services/container_manager.py, agenta-backend/agenta_backend/services/templates_manager.py
- Adjust importing resources using docker client only for the right environments.
- Moved 2 methods to the templates manager as they belongs there.
=> import resources using docker client only for the right environments

agenta-backend/agenta_backend/routers/app_router.py, agenta-backend/agenta_backend/services/db_manager.py
This PR resolves the race condition bug.
- Removed `await engine.save(app_variant_db)`  to prevent race conditions during deployment updates.
- Set `await` to ensure validate_image in the deployment manager runs successfully.
Closes #904
=> [Bug Fix]: Resolve race condition => Base deployment issue

agenta-backend/agenta_backend/config.py, agenta-backend/agenta_backend/config.toml, agenta-backend/agenta_backend/services/app_manager.py, agenta-backend/agenta_backend/utils/redis_utils.py, docker-compose.gh.yml, docker-compose.prod.yml, docker-compose.test.yml, docker-compose.yml
This PR moves redis url configuration from config.toml to an environment variable
Closes #915
=> Enhancement - Move Redis URL Configuration from config.toml to an Environment Variable

agenta-backend/agenta_backend/routers/testset_router.py
A row in a CSV file can have multiple lines. However the following code will be broken if the row has multiple lines.
```python
csv_reader = csv.reader(csv_text.splitlines())
```
We better utilize the csv.DictReader to read the csv file.
=> Fix #924: use csv.DictReader to read csv file

agenta-cli/agenta/cli/helper.py, agenta-cli/agenta/cli/main.py, agenta-cli/agenta/cli/variant_configs.py
Currently, the CLI defaults to the cloud backend host when the cloud option is selected, which may not be desirable for all use cases. With this update, users can set the URL they want to use, enabling them to seamlessly switch between the various environment of Agenta as per their development needs. 
To set the URL, run the command, `agenta config set-host https://example.com`.
Closes [C_180](https://github.com/Agenta-AI/agenta_cloud/issues/180)
=> Enhancement - Add support for configurable Agenta Cloud URL in CLI

agenta-cli/agenta/__init__.py, agenta-cli/agenta/sdk/__init__.py, agenta-cli/agenta/sdk/agenta_decorator.py, agenta-cli/agenta/sdk/types.py
This PR marks the initial implementation stage of integrating file input functionality, such as images and PDFs, into our LLM applications. 
To utilize the SDK input, follow these steps:
```python
import agenta as ag
from agenta import TextParam, FloatParam, FileInputURL
..................
..................
ag.init(app_name="linkedin_generator", base_name="app")
..................
..................
@ag.entrypoint
def generate(
attachment_url: FileInputURL,
) -> dict:
```
Closes first issue in #944
=> Feat - Introducing FileInputURL SDK Type for LLM Applications

agenta-backend/agenta_backend/routers/testset_router.py, agenta-web/src/components/TestSetTable/TestsetTable.tsx, agenta-web/src/lib/helpers/evaluate.ts, agenta-web/src/lib/helpers/fileManipulations.ts, agenta-web/src/lib/helpers/utils.ts, agenta-web/src/pages/apps/[app_id]/testsets/new/upload/index.tsx
=> 948 | Fix: Error handling for malformed file uploads in testsets

agenta-backend/agenta_backend/services/evaluation_service.py
This PR resolves #992 
When the input names in the variant doesn't match the input in the testset, the error is returned properly.
=> Fix 500 error in non-match testset vs variant input names

agenta-web/cypress.config.ts
@mmabrouk This pull request only runs the Cypress tests that are currently passing while I work on the rest that keep failing
=> Exclude failing tests

agenta-backend/agenta_backend/services/docker_utils.py
=> [Bug Fix]: Resolve communication issue between Linux-based variants and backend

agenta-backend/agenta_backend/services/app_manager.py, agenta-backend/agenta_backend/services/db_manager.py
In Python, when we use list comprehensions, it's like we've created the entire pile of apples and asked the interpreter to hold onto it. Sometimes, a better practice involves using generator expressions, which create iterators that yield objects one at a time. For large data sets, this can turn a slow, memory-intensive operation into a relatively fast one. What do you think?
Using generator expressions instead of list comprehensions can lead to better performance. This is especially true for functions such as anywhere it's not always necessary to evaluate the entire list before returning. For other functions such as max or sum it means that the program does not need to store the entire list in memory. These performance effects become more noticeable as the sizes of the lists involved grow …
=> Use Generator Expressions Instead of List Comprehensions

agenta-web/src/components/AppSelector/AppSelector.tsx, agenta-web/src/components/Playground/Views/ParametersView.tsx, agenta-web/src/components/Playground/Views/PublishVariantModal.tsx, agenta-web/src/contexts/profile.context.tsx, agenta-web/src/hooks/usePostHogAg.ts, agenta-web/src/hooks/useSession.ts, agenta-web/src/pages/_app.tsx
The PR achieves the following:
- synchronizes OSS tracking (UI) with CLI
- tracks the user email in cloud and user id in oss
- tracks new events on the UI: $page_view, variant_saved & app_deployed
- created a reusable hook for poshog tracking
Closes [ag_199](https://github.com/Agenta-AI/agenta_cloud/issues/199) x [ag_198](https://github.com/Agenta-AI/agenta_cloud/issues/198)
=> Enhancement - Synchroize OSS UI telemetry tracking with CLI

agenta-cli/agenta/sdk/agenta_decorator.py, examples/async_startup_technical_ideas/app.py, examples/async_startup_technical_ideas/requirements.txt
This PR enhances the SDK to support asynchronous operations while also maintaining backward compatibility for synchronous use.
Closes #317 
LLM app(s) currently using only the `def` keyword have backward compatibility. The included llm example in this PR utilizes the `async def` keyword in the function and also the OpenAI Async SDK, enhancing performance.
=> Enhancement - refactor SDK to support asynchronous operations

agenta-cli/agenta/sdk/agenta_init.py, agenta-cli/pyproject.toml
This pull request updates the version of the `agenta` SDK to 0.6.3 and adds a new method `register_default` as an alias for the existing `default` method. The `register_default` method allows for easier registration of default parameters. This change improves the usability and flexibility of the SDK.
=> Update version to 0.6.3 and add register_default method as an alias for default

agenta-cli/agenta/__init__.py, agenta-cli/agenta/sdk/__init__.py, agenta-cli/agenta/sdk/agenta_decorator.py, agenta-cli/agenta/sdk/types.py, agenta-web/src/components/Playground/Views/ParametersCards.tsx, agenta-web/src/lib/helpers/openapi_parser.ts, examples/chat_json_format/app.py, examples/chat_json_format/requirements.txt
This PR accomplishes the following:
- Designs a metaclass to manage the behavior of a boolean without direct inheritance
- Creates a new sdk type that inherits from the above metaclass and int
- Modifies the frontend openapi parser to identify the sdk type with its x-param
- Updates the frontend playground to use a switch toggle widget if a binaryparam (boolean) type is used
Closes #1044
=> Feat - Implemented BinaryParam SDK type

agenta-cli/agenta/sdk/types.py, agenta-web/src/components/Playground/Views/ParametersCards.tsx, examples/chat_json_format/app.py
This PR removes the BoolMeta metaclass and inheritance from BinaryParam class.
Resolves [pullrequestreview-1789008304](https://github.com/Agenta-AI/agenta/pull/1052#pullrequestreview-1789008304)
=> Enhancement - refactor BinaryParam SDK type

agenta-cli/agenta/client/client.py, agenta-cli/agenta/config.py
This PR fixes;
- Deleting Variants in Cloud: This was caused by a missing `/` in the endpoint url. It works without using Localhost but not in Cloud due to Server Configuration.
=> Fix removing variants in cloud

agenta-web/src/components/Playground/AddToTestSetDrawer/AddToTestSetDrawer.tsx
This pull request adds a Tooltip component to the AddToTestSetDrawer file. The Tooltip provides a description and functionality for adding all conversation turns as individual data points. This enhancement improves the user experience and makes it easier to add multiple exchanges in a conversation.
=> Add Tooltip for adding all conversation turns in AddToTestSetDrawer

agenta-web/src/components/Playground/Views/TestView.tsx
Add cost, latency, tokens to playground
Issue #988 
Sub issue #1059
=> Add cost, latency, tokens to playground

agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx, agenta-web/src/components/EvaluationTable/AICritiqueEvaluationTable.tsx, agenta-web/src/components/EvaluationTable/CustomCodeRunEvaluationTable.tsx, agenta-web/src/components/EvaluationTable/ExactMatchEvaluationTable.tsx, agenta-web/src/components/EvaluationTable/RegexEvaluationTable.tsx, agenta-web/src/components/EvaluationTable/SimilarityMatchEvaluationTable.tsx, agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx, agenta-web/src/components/EvaluationTable/WebhookEvaluationTable.tsx, agenta-web/src/components/Playground/Views/TestView.tsx, agenta-web/src/lib/services/api.ts
=> Make new SDK work with evaluation

agenta-backend/agenta_backend/routers/configs_router.py, agenta-backend/agenta_backend/services/app_manager.py, agenta-cli/agenta/sdk/agenta_init.py
This PR fixes the issues in #1102
The issue was that each time register_default was called, the default configuration was resetted to the default specified in the code. In lambda this meant that at each call, the default configuration was resetted.
The solution was to:
- Change the behavior of register_default so that it does not overwrite the parameters unless they are empty (set to {})
- Each time we create a new application or overwrite a new application, we set the parameters to {}
As a result, now register_default only sets the parameters the first time post-deployment. After that it does not do anything. 
Potential issues: Right now POST config now returns an error when register_default is called. Are we handling this?
=> Fix register_default overwrite behavior

agenta-backend/agenta_backend/models/converters.py, agenta-backend/agenta_backend/models/db_models.py, agenta-backend/agenta_backend/routers/evaluation_router.py, agenta-backend/agenta_backend/routers/evaluators_router.py, agenta-backend/agenta_backend/routers/human_evaluation_router.py, agenta-backend/agenta_backend/services/db_manager.py, agenta-backend/agenta_backend/services/evaluation_service.py, agenta-backend/agenta_backend/services/evaluators_service.py, agenta-backend/agenta_backend/services/llm_apps_service.py, agenta-backend/agenta_backend/tasks/evaluations.py
- Lightly tested with simple prompt template (works)
- Now testing with cli applications
- The way we handle inputs (@aakrem and @aybruhm please take a look at this for the future)
- Call to evaluate (mix-up outputs / correct_answer)
- Failure state not propagating to FE
- Chat applications working, however the test set outputs is saved wrongly in FE
Additionally I refactored the inputs to the evaluate task and the evaluation services.
=> Refactor evaluations backend

agenta-backend/agenta_backend/services/llm_apps_service.py, agenta-backend/agenta_backend/tasks/evaluations.py
This pull request fixes an issue with dynamic inputs in the eval function. Previously, when using dynamic inputs, the inputs were not being properly handled, resulting in incorrect behavior. This PR updates the code to correctly handle dynamic inputs, ensuring that the eval function works as expected.
Now before we save the inputs the first time, we use the default values provided in the openapi,json
=> Fix issue with dynamic inputs in eval

agenta-backend/agenta_backend/models/api/evaluation_model.py, agenta-backend/agenta_backend/models/converters.py, agenta-backend/agenta_backend/models/db_models.py, agenta-backend/agenta_backend/routers/variants_router.py, agenta-backend/agenta_backend/services/db_manager.py, agenta-backend/agenta_backend/services/evaluation_service.py, agenta-web/src/lib/Types.ts
Added variant revision to schemas in evaluation and humanevaluation. 
When we create a new evaluation (both kinds) the backend always links the last revision for each variant to the evaluation document. 
When we GET the evaluation, we provide the ids of the revisions, and the number of the revisions linked to that evaluation (normal and human evaluation)
=> Issue 1210/prompt versioning connecting evaluation

agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240110001454_initial_migration.py, agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240110132547_create_exact_match_evaluator_config.py, agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240110165900_evaluations_revamp.py, agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240112120721_evaluation_scenarios_revamp.py, agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240112120740_human_a_b_evaluation_scenarios.py, agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240112120800_human_single_model_evaluation_scenarios.py, agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240113131802_new_evaluation_results_aggregation.py, agenta-backend/agenta_backend/migrations/17_01_24_pydantic_and_evaluations/20240113204909_change_odmantic_reference_to_link.py, agenta-backend/agenta_backend/migrations/24_01_24_error_and_result/20240124174954_evaluation_error_handling.py, agenta-backend/agenta_backend/migrations/24_01_24_error_and_result/20240124225808_evaluation_scenario_error_handling.py, agenta-backend/agenta_backend/migrations/30_01_24_prompt_versioning/20240130133518_updating_app_variant.py, agenta-backend/agenta_backend/migrations/30_01_24_prompt_versioning/20240130133544_create_app_variant_revision.py, agenta-backend/agenta_backend/migrations/30_01_24_prompt_versioning/20240130133603_updating_app_environment.py, agenta-backend/agenta_backend/migrations/30_01_24_prompt_versioning/20240130140202_connection_evaluation.py, agenta-backend/agenta_backend/models/api/organization_models.py, agenta-backend/agenta_backend/models/api/user_models.py, agenta-backend/agenta_backend/models/db_models.py, agenta-backend/agenta_backend/services/db_manager.py, agenta-backend/agenta_backend/services/evaluation_service.py, agenta-backend/agenta_backend/services/event_db_manager.py, agenta-backend/agenta_backend/tests/variants_main_router/conftest.py
Making use of UTC timezone when inserting a record or records with Python to the mongo database results in a weird behaviour; making use of the same timestamp, even after some minutes intervals. This PR fixes that by changing from UTC timezone to the server timezone. 
UTC Timezone:
Server Timezone:
=> Enhancement - make use of server timezone instead of utc

agenta-backend/agenta_backend/services/db_manager.py, agenta-cli/agenta/sdk/agenta_init.py
After creating an app from the CLI or UI with the system prompt as follows: "You are an expert in geography." and publish the variant to an environment. If you update the system prompt to include "Answer in Japanese." and publish it to the same environment, calling the endpoint will return responses in English. This PR fixes that bug.
With Bug:
```bash
curl -X POST http://localhost/65bcc828fb1a67f973179d13/erd/app/generate_deployed -H "Content-Type: application/json" -d '{
"inputs": {
"country": "Nigeria"
},
"environment": "development"
}'
{"message":"The capital of Nigeria is Abuja.","usage":{"completion_tokens":8,"prompt_tokens":25,"total_tokens":33},"cost":5.35e-05,"latency":2.6593}
```
Bug Fix:
```bash
curl -X POST http://localhost/65bcc828fb1a67f973179d13/country_generator/app/generat …
```
=> Bug Fix: Variant Envrionment Deployment

agenta-backend/agenta_backend/services/evaluation_service.py
This PR resolves the KeyError when creating a human evaluation with a testset data that does not have the correct_answer column.
Closes #1331
=> Bug Fix: Allow Null Correct Answer in Human Annotations Testset

agenta-cli/agenta/cli/main.py, agenta-cli/pyproject.toml
When creating an app from the CLI using the latest SDK version (0.12.1), you will get the following error:
`Error: cannot access local variable 'filtered_org' where it is not associated with a value`
This PR resolves the error
=> [HOT FIX]: Resolved unbound error

agenta-cli/agenta/client/backend/types/app_variant_output.py, agenta-cli/pyproject.toml
This PR fixes a bug that occurs when reserving a variant from the CLI in OSS.
```bash
Checking and updating config file...
Failed during configuration check.
Error message: 1 validation error for ParsingModel[List[agenta.client.backend.types.app_variant_output.AppVariantOutput]]
__root__ -> 0 -> organization_id
field required (type=value_error.missing)
```
Merging this PR will update the agenta (SDK) version in pypi to 0.12.5
=> CLI: Resolve bug causing variant not to serve (again)

agenta-web/src/lib/services/api.ts
This PR resolves the issue of saving an empty prompt, which results in re-initializing the prompt. The problem was this line of code: `.filter((param) => param.default)`, which strips off parameters without a default value (even if there was one). 
Closes #1462
=> Bug Fix - remove .filter() logic that removes parameters that don't have a value

agenta-cli/agenta/cli/main.py
Closes  #1469
The issue is that when calling the api authentication endpoint without the right key, we don't get a 401 but a 500. This should be fixed in the backend side, this just a hotfixe to the error message.
@aybruhm can you please look into the core issue (us not returning 401 but 500 when authentication failes). @aakrem This is the right behavior, no?
=> Hotfix when API key is wrong in CLI

agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
Currently, when an error occurs in the evaluation, the UI displays error messages within rows. However, users are unable to expand these rows to view the full error message.
=> Fix: Allow expanding rows to display full error messages

agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx, agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx
=> Hide latency and cost columns on filter

docker-compose.gh.yml
This pull request fixes the issue with the gh docker compose. The celery_worker service in the docker-compose.yml file has been updated to use the image from ghcr.io/agenta-ai/agenta-backend and the watchmedo command has been removed from the command section.
=> Fix issue with gh docker compose

agenta-backend/agenta_backend/services/deployment_manager.py, agenta-backend/agenta_backend/services/docker_utils.py, agenta-cli/agenta/cli/main.py, agenta-cli/agenta/docker/docker_utils.py
This PR renames `.gitignore` to `.agentaignore` and prevents it from being overwritten when re-running `agenta init`.
Closes #1509
During testing, I encountered an issue where starting a variant failed after successfully building the variant Docker image. This was caused by an incorrect repository name in line 15 of `agenta-backend/agenta_backend/services/deployment_manager.py` and line 13 of `agenta-backend/agenta_backend/services/docker_utils.py`. This error has also been fixed in this PR.
=> [Bug Fix]: gitignore are overwritten when runnning agenta init

agenta-backend/agenta_backend/services/llm_apps_service.py
This PR improves the batch processing logic to run in parallel rather than sequentially.
Closes #1538
=> [Perf]: increase batch invoke by rewriting http call logic using aiohttp

agenta-web/src/components/TestSetTable/TestsetTable.tsx
=> [Bug Fix]: Rendering UI bug in Testset view 

agenta-cli/agenta/cli/variant_commands.py
This PR refactors the start_variant function in the CLI to make use of the appropriate type and also accesses the uri from the deployment. See screenshot below:
Closes #1257
=> [Bug Fix]: urls shown when running agenta variant serve are wrong

agenta-backend/agenta_backend/models/api/evaluation_model.py, agenta-backend/agenta_backend/models/converters.py, agenta-backend/agenta_backend/models/db_models.py, agenta-backend/agenta_backend/services/aggregation_service.py, agenta-backend/agenta_backend/tasks/evaluations.py, agenta-cli/agenta/client/backend/types/evaluation.py, agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx, agenta-web/src/lib/Types.ts, agenta-web/src/services/evaluations/index.ts
Notes:
- The total cost value of each evaluation scenario is rounded to the ten-thousandth place. For example, a value of 0.00006050000000000001 will display as 0.0001.
Therefore summing what we see in the evaluation scenarios results view and compare it to what we have in the evaluation results view won't make much of sense. But maybe we need to explain this somewhere.
- For old evaluations will will display "-"  as the total cost is not there.
- Kept average cost in case we need it in the future and also to prevent doing a migration.
=> add total latency

docs/advanced_guides/using_agenta_from_cli.mdx
This pull request adds the documentation ability to add multiple app variants to a single application using the CLI. This is useful for testing different workflows for the same application. To add a new variant, create a new python file with the new logic and execute the command `agenta variant serve <new_filename.py>`. The new variant will be labeled `<new_filename>.default` in the UI, and you can modify its configuration in the playground.
=> Add multiple variants for one application

agenta-backend/agenta_backend/services/llm_apps_service.py, agenta-backend/agenta_backend/utils/common.py
This pull request adds a traceback for error handling in the LLM Apps service. The traceback is generated using the `traceback` module and provides more detailed information about the error that occurred during app invocation.
It also instruments evaluation exceptions in sentry
=> Add traceback for error handling in LLM Apps service

agenta-cli/agenta/cli/variant_commands.py, docs/developer_guides/cli/quick-usage.mdx
- Added an --overwrite flag that enables overwriting an app without requiring interactive mode.
- Interactive mode functions as it did before.
=> Optional interactive mode

agenta-cli/agenta/docker/docker-assets/Dockerfile.template
This PR modifies the permissions of `entrypoint.sh` within the `Dockerfile.template` to make it executable when the `serve` command is executed.
Closes #1588
=> Build: change permission of 'entrypoint.sh' to be executable

docs/prompt_management/integrating.mdx
The images for middleware and prompt management system are flipped in the docs for integrating
=> fix: swap images in docs

agenta-web/src/components/pages/evaluations/FilterColumns/FilterColumns.tsx, agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx, agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx, agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx, agenta-web/src/lib/Types.ts, agenta-web/src/lib/helpers/evaluate.ts, agenta-web/src/services/evaluations/index.ts
Issue [#1395](https://github.com/Agenta-AI/agenta/issues/1395)
Depends on #1606
=> [Sub issue]: Improve Evaluation comparison view to show all ground truth columns

.github/workflows/cli-commands-tests.yml, agenta-cli/agenta/cli/main.py, docs/reference/cli/init.mdx
- added organisation option in cli for non interactive mode
- added cli commands for cloud
=> Workflow for cli commands for cloud

agenta-web/src/components/Playground/Views/GroupedSelect.tsx
This pull request addresses an issue where the `key` prop in the ModelName component was returning undefined values. The key prop was conflicting with React's internal usage, leading to unexpected behavior. By renaming the prop to `value`, the conflict is resolved, and the component functions correctly.
=> Fix key prop issue in ModelName component

.github/actions/check-app-accessibility/action.yml, .github/workflows/cli-commands-tests.yml
- Add a step to check the accessibility of an app after serving it
- introduced composite action to prevent duplicated code
=> add action to check the app accessibility after serving

agenta-backend/agenta_backend/services/security/sandbox.py
Hey, I noticed arguments were fed out of order for custom code evaluators. 
This is the template for the proposed custom evaluator 
```python
from typing import Dict
def evaluate(
app_params: Dict[str, str],
inputs: Dict[str, str],
output: str,
correct_answer: str
) -> float:
return 0.75  # Replace with your calculated score
```
But currently evaluators are invoked with `result = environment["evaluate"](app_params, inputs, correct_answer, output)`
To me the argument order in the template makes more sense, but it might not be backward compatible for people that worked around it by modifying the signature of the "evaluate" method. 
Let me know which options sounds best to you and I can expand the PR in the desired direction :)
=> Fixes argument order for custom code evaluator

agenta-backend/agenta_backend/services/llm_apps_service.py, agenta-backend/agenta_backend/tests/unit/test_llm_apps_service.py
Added Unit Tests for the llm_apps_service.py :
- Success, retries, and generic exception cases.
Improved run_with_retry method:
- Prevented infinite loops.
=> Tests for llm apps service

agenta-web/src/components/Playground/ViewNavigation.tsx, agenta-web/src/lib/services/api.ts
Depends on [#369](https://github.com/Agenta-AI/agenta_cloud/pull/369)
=> [Enhancement]: Logs are not fetched in cloud

agenta-web/src/components/ChatInputs/ChatInputs.tsx, agenta-web/src/components/CopyButton/CopyButton.tsx, agenta-web/src/components/Playground/ParamsForm/ParamsForm.tsx, agenta-web/src/components/Playground/Views/TestView.tsx
=> Move copy message button in the playground to the text input

agenta-web/src/components/Playground/AddToTestSetDrawer/AddToTestSetDrawer.tsx
=> When adding a data point to a test set, there is never a default set selected

agenta-web/src/components/Playground/ViewNavigation.tsx, agenta-web/src/lib/services/api.ts
Reverts Agenta-AI/agenta#1685
Reverting this PR as it's breaking the familiar behavior of opening an app once it got created.
We are displaying logs faster then waiting the the app from being ready
=> Revert "[Enhancement]: Logs are not fetched in cloud"

agenta-web/src/components/Playground/Views/TestView.tsx, agenta-web/src/lib/helpers/formatters.ts
This pull request addresses a specific use case where the formatter function receives an `undefined` value. In such cases, the function will return `0`
Depends on [#58](https://github.com/Agenta-AI/agenta-commons/pull/58)
=> Added fallback value for undefined parameters

agenta-cli/agenta/sdk/types.py
=> Fixes Warning: Default value gpt-3.5-turbo provided but choices are empty.

agenta-web/src/components/Playground/Views/GroupedSelect.tsx, agenta-web/src/pages/apps/[app_id]/annotations/human_a_b_testing/[evaluation_id]/index.tsx, agenta-web/src/pages/apps/[app_id]/annotations/single_model_test/[evaluation_id]/index.tsx
Fixed the select model componnet search bar by replacing `getTextContent` function with the `options.value` as search query.
Majority of the times the `getTextContent` function return empty string that's why the result was showing empty by replacing it with `options.value` the search bar is functioning now.
Closes #1717
=> Fix: select model component search bar

agenta-backend/agenta_backend/services/evaluators_service.py
**Issue:**
Previous evaluators have not been correctly migrated to include the [correct_answer](file:///Users/mahmoudmabrouk/agenta/code/agenta-core/agenta-backend/agenta_backend/services/evaluators_service.py#33%2C32-33%2C32) setting key.
**Proposed Solution:**
The proper solution is to add a migration that inserts this key with the default value [correct_answer](file:///Users/mahmoudmabrouk/agenta/code/agenta-core/agenta-backend/agenta_backend/services/evaluators_service.py#33%2C32-33%2C32) whenever it does not exist.
**Hotfix:**
This hotfix sets the default to [correct_answer](file:///Users/mahmoudmabrouk/agenta/code/agenta-core/agenta-backend/agenta_backend/services/evaluators_service.py#33%2C32-33%2C32) at runtime if the setting does not exist. However, this is not ideal as it can …
=> Hotfix evaluation

agenta-backend/agenta_backend/tasks/evaluations.py
One call in evaluation had a wrong argument. This resulted in the failure of evaluation in the case of the failure in th invocation of the llm app
=> Evaluation fix

agenta-web/src/components/TestSetTable/TestsetTable.tsx
Fixed the test set colums naming conventions by making it lowercase.
**Screenshot**
**Issue**
Closes #1737
=> fix: fixed testset columns naming conventions

agenta-web/src/components/Playground/Views/ParametersCards.tsx
=> fix(app): #1747 Fix showing params in the playground

agenta-cli/agenta/sdk/decorators/llm_entrypoint.py
This hotfix assigns `None` as the default value to the `usage` and `cost` fields within the `FuncResponse` SDK type for LLM app outputs that are of type string.
=> fix (sdk): set default values to FuncResponse sdk type

agenta-web/src/components/pages/evaluations/cellRenderers/cellRenderers.tsx, agenta-web/src/components/pages/evaluations/evaluationCompare/EvaluationCompare.tsx, agenta-web/src/components/pages/evaluations/evaluationResults/EvaluationResults.tsx, agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
- Added export button for CSV export
- Implemented row selection for customized exports
Closes #1696
=> [Feature]: Export results in the Evaluation Scenarios view

agenta-backend/agenta_backend/services/evaluators_service.py, docker-compose.test.yml
This PR resolves the `ChatComletionMessage is not subscriptable` error when running auto ai critique evaluation.
Full Error Traceback:
```python
[2024-06-07 13:39:28,371: DEBUG/ForkPoolWorker-1] Result: evaluator_config=ObjectId('666309d686a85ea3911dbc99') result=Result(type='error', value=None, error=Error(message='Error during Auto AI Critique', stacktrace="'ChatCompletionMessage' object is not subscriptable"))
[2024-06-07 13:39:28,403: ERROR/ForkPoolWorker-1] Task agenta_backend.tasks.evaluations.evaluate[67ad4369-e935-42e2-b400-fc962af27510] raised unexpected: TypeError('expected string or bytes-like object')
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 453, in trace_task
R = retval = fun(*args, **kwargs)
File …
```
=> [Hotfix]: resolve ChatCompletionMessage object is not subscriptable

agenta-backend/agenta_backend/services/llm_apps_service.py
Just made sure not add a parameter if it not already in the db
=> fix(backend): candidate hotfix for failing evals

agenta-backend/agenta_backend/services/app_manager.py, agenta-cli/agenta/sdk/agenta_init.py, agenta-cli/pyproject.toml
Publishing a variant to an environment currently fails to pull the environment's configuration due to an invalid API key, causing unexpected behaviour. This PR resolves the issue.
=> Fix: error when pulling environment configuration

agenta-web/src/components/Playground/NewVariantModal.tsx, agenta-web/src/components/Playground/Playground.tsx
Cleared the input data from the 'Create a New Variant' modal after successfully creating a variant to enhance user experience.
**Issue**
Closes #1790
=> Fix: cleared 'Create a New Variant' modal input data

README.md
This Pull Request addresses the issue of broken links in the GitHub README file that were previously pointing to incorrect parts of the documentation.
Closes [AGE-317](https://linear.app/agenta/issue/AGE-317/fix-docs-links-from-github-and-inside-the-docs)
=> docs(tool): Fix docs links from github and inside the docs

agenta-backend/agenta_backend/models/db_engine.py, agenta-backend/agenta_backend/tests/conftest.py, docker-compose.test.yml
This PR addresses the issue of failing backend tests due to improper database (sqlalchemy async engine) initialization. The changes ensure that the database is correctly set up before tests run, preventing the failures.
- **Move initialization of async SQLAlchemy engine to the __init__ method:** Ensures that the engine is properly configured when the class is instantiated.
- **Instantiate DBEngine class to a variable instance:** Provides a consistent and reusable database engine instance across the lifecycle of the tests session.
The backend tests were failing because the async engine was not properly initialized. By moving the initialization of the SQLAlchemy engine to the `__init__` method and ensuring the `DBEngine` class is properly instantiated, we ensure that the database connection …
=> [Enhancement]: Resolve Failing Backend Tests 

agenta-backend/agenta_backend/services/db_manager.py
This PR ensures that only the targeted variant's environment is affected by the deletion.
When a variant is deleted, it automatically sets the `deployed_app_variant_id` and `deployed_app_variant_revision_id` fields in the environment to `NULL`. This means that the variant that was published to an environment has its `deployed_app_variant_id` and `deployed_app_variant_revision_id` fields set to `NULL`.
=> Bug fix/variant deletion unpublish other variants environment

agenta-backend/agenta_backend/models/converters.py, agenta-backend/agenta_backend/routers/evaluation_router.py
- Catch None-related issue in Optional[...] field: EvaluationResult.correct_answers
- Adds logger.error(e) for exception in evaluation router
**Related Issues**
Not linked yet.
=> Fix issue where Evaluation Results don't load when individual Evaluation Scenarios fail

agenta-backend/agenta_backend/services/evaluators_service.py, agenta-backend/agenta_backend/tasks/evaluations.py, agenta-web/src/components/pages/evaluations/cellRenderers/cellRenderers.tsx
Uses `traceback` to better handle stacktraces and then shows the stacktrace in a tooltip in the web UI.
**Related Issues**
Not linked yet.
=> Fix incomplete stacktraces in evaluations

agenta-cli/agenta/sdk/decorators/llm_entrypoint.py, agenta-cli/agenta/sdk/decorators/tracing.py, agenta-cli/pyproject.toml
Func errors used to be set as func result. Now they are propagated up by forwarding the exception up (raise e).
=> fix(sdk): AGE-272 Propagate func errors up in @ag.instrument() wrappers

agenta-backend/agenta_backend/services/db_manager.py
This PR adds a function to fetch the corresponding object UUID (as string) from the database.
```python
from agenta_backend.services import db_manager
...
app_object_id = "66893cd16c27dd6b19d2230b"
app_uuid_as_str = await db_manager.fetch_corresponding_object_uuid(
table_name="app_db", object_id=app_object_id
)
print(app_uuid_as_str) 
```
=> Refactor/add function to fetch corresponding object UUID

agenta-backend/agenta_backend/services/db_manager.py
This PR addresses the issue by implementing a new function, `get_object_uuid`, in the db_manager. The function ensures that the `app_id` is correctly interpreted as a UUID. The `list_variants` and `build_image` endpoints have been updated to use this function, ensuring compatibility between the CLI and backend.
- Added `get_object_uuid` function to db_manager.
- Updated `list_variants` and `build_image` endpoints to use the new function.
=> [Bug Fix]: CLI config (app_id) mismatch with backend UUID handling

docker-compose.gh.yml, docker-compose.yml
This PR enhances the `gh compose` configuration for production use by introducing PostgreSQL and PgAdmin services. Additionally, it adds the necessary database source configuration to make possible for data migration from MongoDB to PostgreSQL.
=> [Feature]: Added postgres to gh compose for production use

agenta-backend/agenta_backend/routers/app_router.py
To be tested in cloud-dev.
Replaces hard-coded hack.
=> fix(backend): Fixes use of feature flag for local cloud dev with templates

agenta-backend/agenta_backend/migrations/mongo_to_postgres/db_engine.py, agenta-backend/agenta_backend/migrations/mongo_to_postgres/migration.py, agenta-backend/agenta_backend/migrations/mongo_to_postgres/utils.py, agenta-backend/agenta_backend/models/db_engine.py
The code was used when working on migration with main goal is to have a fresh state of tables when we adjust the migration script.
=> refactor(backend): remove code for deleting db and tables

agenta-backend/agenta_backend/models/converters.py, agenta-backend/agenta_backend/routers/container_router.py, agenta-backend/agenta_backend/services/db_manager.py, agenta-web/src/components/Playground/Views/ParametersView.tsx
This PR:
- Adds backward compatibility logic to handle deleted variants in human evaluations, ensuring that the UI remains functional even when associated variants are deleted.
- Ensures that testsets in use by human evaluations cannot be deleted.
Closes [AGE-414](https://linear.app/agenta/issue/AGE-414/[bug]-human-evaluation-ui-breaks-when-a-variant-has-been-deleted)
- Updates the `fetch_evaluations_by_resource` function in `db_manager` to retrieve both human and automatic evaluations for the `testset` & `variant` resource type. This ensures that users are notified of the number of resources using the testset or variant before deletion.
- Updates the `construct_app_container_url` router to handle backward compatibility when viewing a single human evaluation after a variant is deleted. …
=> [Bug fix]: Human evaluation UI breaks when a variant has been deleted

agenta-backend/agenta_backend/routers/container_router.py
This PR is a hot fix in the backend to address the issue where permission access for application being triggered when the variant had been deleted.
[AGE-414](https://github.com/Agenta-AI/agenta/pull/1872)
- Updated condition to ensure that permission to view evaluation is triggered only when `object_db` is provided.
=> [Hot fix]: ignore permission to check human evaluation access in the case object_db is None

agenta-web/src/lib/helpers/evaluate.ts
Fix Custom Comparator to Convert Boolean Type to Text
Closes [AGE-419](https://linear.app/agenta/issue/AGE-419/[bug]-typeerror-elocalecompare-is-not-a-function)
1. Create an evaluator, e.g., Exact Match.
2. Start a new evaluation with the evaluator.
3. Go to the Evaluation Results page.
4. Click on the Evaluator column with boolean values to rearrange the order.
5. See Error.
https://github.com/user-attachments/assets/8566b725-1cf2-4156-a6f3-3283d2738018
=> [Bug] TypeError: e.localeCompare is not a function

agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx, agenta-web/src/components/Evaluations/EvaluationCardView/index.tsx
This Pull Request addresses an issue in the Single Model Test Evaluation where modifications made to the Expected Output column are not saved when creating a new test set.
Closes [AGE-399](https://linear.app/agenta/issue/AGE-399/[bug]-test-creation-in-single-model-eval-does-not-work-in-table-view)
1. Create a single model evaluation.
2. Move to table view.
3. Create an annotation (modify the correct answer).
4. Click on Save test set.
5. You will find that the newly created test set does not include the modifications you made.
[Jam Recording](https://jam.dev/c/f8146d1c-52e6-45bc-b325-16201a7fa7da)
=> fix(frontend): Test creation in single model eval does not work in table view

agenta-web/src/pages/_app.tsx, agenta-web/src/pages/_document.tsx
**Description:**
`Warning: <title> should not be used in _document.js's <Head>.` 
Fixed the title warning issue by moving the title element from the`_document.tsx` file to the `_app.tsx` file.
**Resources:**
- [<title> should not be used in _document.js <Head>](https://nextjs.org/docs/messages/no-document-title)
- [Missing Document Components](https://nextjs.org/docs/messages/missing-document-component)
=> Fix: resolved the title warning issue

agenta-backend/agenta_backend/pytest.ini, agenta-backend/agenta_backend/resources/evaluators/evaluators.py, agenta-backend/agenta_backend/services/evaluators_service.py, agenta-backend/agenta_backend/tasks/evaluations.py, agenta-backend/agenta_backend/tests/unit/test_evaluators.py, agenta-web/src/lib/enums.ts, agenta-web/src/lib/helpers/utils.ts, agenta-web/src/services/evaluations/api/index.ts
This PR introduces a JSON Diff Evaluator that compares the structure and content of two JSON objects (ground truth and application output). The evaluator flattens both JSON objects and compares their fields, providing a similarity score. This implementation includes additional features for advanced configuration.
Closes [AGE-286](https://linear.app/agenta/issue/AGE-286/create-a-json-evaluator)
- **Flattening JSON Objects**: Recursively converts nested JSON objects into a single-level dictionary with hierarchical keys.
- **Key Comparison Settings**:
- `predict_keys`: When enabled, includes keys from both ground truth and application output in the comparison.
- `compare_schema_only`: When enabled, compares only the schema (keys and types) rather than the values.
- `case_insensitive_keys`: …
=> [Feature]: Implement JSON Diff Evaluator

agenta-backend/agenta_backend/services/deployment_manager.py, agenta-backend/agenta_backend/services/docker_utils.py, agenta-backend/agenta_backend/tasks/evaluations.py, docker-compose.gh.yml
This PR addresses the issue of the LLM app container being unreachable from the `celery_worker` container when using the GitHub Compose file (docker-compose.gh.yml), causing evaluation to fail.
Closes [AGE-270](https://linear.app/agenta/issue/AGE-270/[bug]-evaluation-fails-when-using-gh-docker-container)
=> [Bug Fix]: evaluation fails when using gh docker container

agenta-cli/agenta/cli/variant_commands.py
**Problem:**
When running agenta variant serve --overwrite, any resulting error is not caught by the CLI, leading to silent failures in our workflows.
**Solution:**
This PR improves error handling by propagating exceptions in add_variant and incorporating sys.exit(1) calls in serve_cli. These enhancements ensure that errors encountered during variant serving are properly caught and reported, causing the CLI and associated GitHub Actions jobs to fail as intended.
**How to QA it:**
Refer to the example of a silent failure (or any similar workflow job triggered from yesterday):
[Silent Fail Example](https://github.com/Agenta-AI/agenta/actions/runs/10072816938/job/27845533928?pr=1856#step:9:18)
**Impact:**
Once this PR is merged, all PRs triggering the serve-to-cloud workflow will fail until …
=> Fix: Ensure CLI catches and reports errors

agenta-cli/agenta/client/backend/resources/observability/client.py, agenta-cli/agenta/sdk/tracing/callbacks.py, agenta-cli/agenta/sdk/tracing/llm_tracing.py, agenta-cli/pyproject.toml
- Uses the updated SDK in litellm callbacks
- Properly serializes litellm errors upon failure, with `repr()`
- AGE-480 : Observability not working for template applications
Use this app [app.py.zip](https://github.com/user-attachments/files/16411705/app.py.zip) with and without `force-json`,
and you should get this :<img width="1405" alt="Screenshot 2024-07-29 at 13 11 43" src="https://github.com/user-attachments/assets/186e9db0-5fa4-4bd5-91a4-5c16d0d61c9b">
=> fix(sdk): AGE-480 Update litellm callbacks with new SDK

agenta-web/src/components/EvaluationTable/ABTestingEvaluationTable.tsx, agenta-web/src/components/EvaluationTable/SingleModelEvaluationTable.tsx
Inreased the max length of the text input in the human eval. The current max rows for the text input for expected correct answer is too small for the screen size and large gts
=> Minor UI improvement at human eval

agenta-cli/agenta/sdk/decorators/llm_entrypoint.py, agenta-cli/agenta/sdk/tracing/callbacks.py, agenta-cli/agenta/sdk/tracing/llm_tracing.py, agenta-cli/agenta/sdk/tracing/tracing_context.py
- Add detached spans (operation can now be performed on `active_span` or on `spans[span_id]`)
- Add `wait_for_spans()` before `dump_trace()` (async span closures now finish before `dump_trace()`), w/ timeout
- Fix litellm callbacks with the two features above
- AGE-504: Fix litellm issue with `dump_trace()`
- run the `single prompt` app from our templates in `oss`
=> fix(sdk): AGE-504 Fix Tracing with LiteLLM

.github/workflows/run-backend-tests.yml, .github/workflows/run-frontend-tests.yml
This PR replaces the use of deprecated docker-compose command to docker compose in the tests' workflow.
See errors:
- https://github.com/Agenta-AI/agenta/actions/runs/10250555963/job/28356547115?pr=1966
- https://github.com/Agenta-AI/agenta/actions/runs/10250555963/job/28356946147?pr=1966
=> fix (workflow): replace deprecated 'docker-compose' command in test workflow

.github/workflows/run-backend-tests.yml, .github/workflows/run-frontend-tests.yml, agenta-backend/agenta_backend/migrations/postgres/README.md, agenta-backend/agenta_backend/migrations/postgres/utils.py, docker-compose.gh.yml, docker-compose.prod.yml, docker-compose.test.yml, docker-compose.yml, docs/self-host/migration/applying-schema-migration.mdx
This PR introduces a db migration service that automatically applies Alembic migrations for first-time users. Returning users can also have migrations applied automatically, depending on the configured environment settings.
Closes [AGE-506](https://linear.app/agenta/issue/AGE-506/enable-automatic-migration-for-first-time-users-and-optionally-for)
- **Clean Up Resources:** Remove all containers, volumes, and images related to Agenta.
- **Start Services:** Run docker-compose up to start the services.
- **Verify Backend Start:** Wait until the backend services are fully started.
- **Test Application Creation:** Navigate to http://localhost/apps and attempt to create an app from a template.
- **Check for Success:** If the templates are visible, Alembic migrations were applied successfully.
=> [Enhancement] Enable automatic migration for first-time users and optionally for returning users

docker-assets/postgres/init-db.sql, docker-compose.gh.yml, docker-compose.prod.yml, docker-compose.test.yml, docker-compose.yml
This PR fixes:
- the clash of postgres containers between oss and cloud
- the fatal error in the postgres error about role does not exist 
```
2024-08-06 10:24:24.775 UTC [40] FATAL:  role "postgres" does not exist
```
NOTES:
- Won't solve the issue of having cloud and oss run together. 
- postgres Volume should be deleted to have this working without issues.
=> fix(tool): AGE-512 fix issues in postgres container

agenta-web/src/lib/helpers/utils.ts
Description:
Fixed the syntax error `SyntaxError: Unexpected token 'N', "Nauru" is not valid JSON` in human evaluation by adding the conditions for better type checking.
=> Fix: human evaluation tests syntax error

agenta-backend/agenta_backend/resources/evaluators/evaluators.py, agenta-backend/agenta_backend/services/evaluators_service.py
Improves the reliabilty of LLM as a judge by using a lower temperature (as done in Ragas for instance) and rename AI critic to the standard name LLM as a judge (in the FE, renaming it in both places would break previously configured evaluators)
=> feat(backend): AGE-276 and AGE-471 Improves LLM-as-a-judge reliability

agenta-backend/agenta_backend/services/db_manager.py, agenta-backend/agenta_backend/services/deployment_manager.py
This PR introduces enhancements to ensure that re-serving a variant in the cloud-dev environment works as expected.
Closes [AGE-511](https://linear.app/agenta/issue/AGE-511/[cli]-cant-re-serve-overwrite-variant-in-cloud-dev)
- **Image Validation Logic Update:**  
- In the cloud-dev environment, certain fields like `workspace` and `organization` are stripped off before validation, since they are not used during this process.
- **App Variant Update Enhancement:**  
- In the cloud-ev environment, the `organization` relationship is now loaded when updating an app variant to ensure the model is fully refreshed in the session.
- **App Creation from the CLI**
- Create and serve an app from the CLI
- Navigate to the app playground URL to ensure that it is working
- Update the app variant …
=> [Bug Fix]: enhance image validation and app variant update logic for cloud-dev environment

agenta-web/src/lib/helpers/utils.ts
- Fixes `BaseResponse` in WebUI when dict-style
- Using SDK v0.21+ (with `BaseResponse`), try a `str`-style output and a `dict`-style output. Both should work.
=> fix(frontend) BaseResponse in WebUI when dict-style

agenta-backend/agenta_backend/routers/app_router.py
This PR fixes a bug where the incorrect permission `UPDATE_APPLICATION` was being used. It has been updated to the correct permission `EDIT_APPLICATION` to ensure consistent access control across the application.
Closes [AGE-539](https://linear.app/agenta/issue/AGE-539/endpoint-for-renaming-an-application)
- Updated permission from `UPDATE_APPLICATION` to `EDIT_APPLICATION` in relevant parts of the codebase.
- Verify that actions requiring the `EDIT_APPLICATION` permission work correctly and that no access issues are introduced.
=> [Bug Fix]: Correct permission naming from 'UPDATE_APPLICATION' to 'EDIT_APPLICATION'

agenta-backend/agenta_backend/migrations/postgres/utils.py
This PR refactors the migration handling process to improve efficiency and accuracy. Key changes include:
- Updated the `get_pending_migration_head` function to compare only the latest migration head with the current state.
- Enhanced the `get_current_migration_head_from_db` function to ensure it returns a single migration head, improving consistency.
- **Migration Check (For First-time User):**
1. Delete all Docker resources related to Agenta on your PC.
2. Run `docker compose up --build` to create new images, volumes, and containers.
3. Apply the Alembic migration with this command:
```bash
docker exec -w /app/agenta_backend/migrations/postgres agenta-backend-1 alembic -c alembic.oss.ini upgrade head
```
- **Migration Check (For Returning User):**
1. Run `docker compose up --build` to …
=> [Enhancement]: Improve pending migration(s) check

agenta-web/src/components/Sidebar/Sidebar.tsx, agenta-web/src/components/pages/overview/abTestingEvaluation/AbTestingEvalOverview.tsx, agenta-web/src/components/pages/overview/automaticEvaluation/AutomaticEvalOverview.tsx, agenta-web/src/components/pages/overview/deployments/DeploymentOverview.tsx, agenta-web/src/components/pages/overview/singleModelEvaluation/SingleModelEvalOverview.tsx, agenta-web/src/components/pages/overview/variants/VariantPopover.tsx
Fixed the small UI issues in the overview page.
- A/B testing datapoints incorrect font size.
- Padding and gap issue on deployment card.
- Truncate long app names in side menu.
- Automatic results popover should be visible on hover.
=> Fix: small UI issues in overview page

agenta-backend/agenta_backend/services/app_manager.py
This PR resolve the `TypeError` got from `create_api_key` service function when starting an application variant docker container in oss/cloud-dev.
Closes [AGE-978](https://linear.app/agenta/issue/AGE-978/[bug]-unable-to-create-new-application)
=> fix (bug): resolve error when starting application variant container

agenta-web/src/code_snippets/endpoints/fetch_config/curl.ts, agenta-web/src/code_snippets/endpoints/fetch_config/python.ts, agenta-web/src/code_snippets/endpoints/fetch_config/typescript.ts, agenta-web/src/pages/apps/[app_id]/testsets/index.tsx
This PR fixes the incorrect endpoint in the OSS deployment fetch prompt and the incorrect redirection to evaluation from the test set.
- Closes [AGE-988](https://linear.app/agenta/issue/AGE-988/[bug]-testset-page-start-evaluation-button-redirecting-to-the-wrong)
- Closes [AGE-971](https://linear.app/agenta/issue/AGE-971/[qa][bug]-wrong-endpoint-in-oss-for-deployment-fetch-prompt-[non)
=> fix(frontend): Wrong endpoint in deployment fetch prompt

agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/EvaluatorsModal.tsx
This PR aims to prevent closing the evaluator config model when clicking outside of it. 
Closes [AGE-1013](https://linear.app/agenta/issue/AGE-1013/clicking-outside-evaluation-configuration-modal-closes-the-modal)
=> fix(frontend): prevent closing eval-config modal when click outside

docs/blog/main.mdx, docs/package-lock.json, docs/package.json
- Added new entry to changelog page
=> [Docs] Changelog Evaluator Debugging

agenta-backend/agenta_backend/routers/app_router.py, agenta-backend/agenta_backend/routers/variants_router.py, agenta-backend/agenta_backend/services/app_manager.py
This PR fixes issues with the Agenta CLI, which stopped working after changes to the project structure were released.
Closes [AGE-1057](https://linear.app/agenta/issue/AGE-1057/agenta-cli-does-not-work-anymore-post-release-project) (Critical)
- [Commons#117](https://github.com/Agenta-AI/agenta-commons/pull/117)
- Fix `AssertionError` when creating an app from the CLI due to a missing `workspace_id`.
- Resolve `TypeError` in `start_variant` function caused by a missing argument after the variant image update.
- Create an app from the CLI while running in cloud-dev environment.
- Re-serve a deployed app to verify that updates are applied correctly.
- Verify that an app can be successfully created from the CLI in the cloud-dev environment without errors.
- Ensure that the created app can be …
=> [Bug Fix]: agenta CLI does not work anymore post-release (project structure) 

docs/blog/main.mdx, docs/docs/evaluation/evaluators/05-rag-evaluators.mdx, docs/docs/getting-started/01-introduction.mdx, docs/docs/getting-started/02-quick-start.mdx, docs/docs/prompt-management/01-overview.mdx, docs/docs/prompt-management/02-quick-start.mdx, docs/docs/prompt-management/03-creating-a-custom-template.mdx, docs/docs/prompt-management/integration/01-how-to-integrate-with-agenta.mdx, docs/docs/reference/api/agenta-backend.info.mdx, docs/docs/self-host/deploy_remotly/host-on-gcp.mdx, docs/docusaurus.config.ts
This PR aims to fix all the broken links we have in the documentation
Closes [AGE-1068](https://linear.app/agenta/issue/AGE-1068/[doc]-fix-all-broken-dead-links)
=> fix(doc): fixed all broken links

agenta-web/src/components/HumanEvaluations/AbTestingEvaluation.tsx, agenta-web/src/components/HumanEvaluations/SingleModelEvaluation.tsx, agenta-web/src/components/pages/overview/automaticEvaluation/AutomaticEvalOverview.tsx, agenta-web/src/components/pages/overview/deployments/DeploymentOverview.tsx, agenta-web/src/components/pages/overview/variants/VariantsOverview.tsx, agenta-web/src/pages/apps/[app_id]/overview/index.tsx
This PR aims to fix the button size issue in app-overview page.
Closes [AGE-928](https://linear.app/agenta/issue/AGE-928/app-overview-update-all-buttons-size-to-default)
=> fix(frontend): converted all the buttons to it's default size in app overview page

docs/docs/misc/contributing/getting-started.mdx, docs/docusaurus.config.ts
This PR aims to improve the workflow of the documentation by detecting broken links at build time.
=> enhance(doc): enabled broken link detector

agenta-web/src/components/HumanEvaluations/AbTestingEvaluation.tsx, agenta-web/src/components/HumanEvaluations/SingleModelEvaluation.tsx, agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx, agenta-web/src/lib/helpers/evaluate.ts
This PR aims to add export data as CSV feature on evaluations.
Closes [AGE-1021](https://linear.app/agenta/issue/AGE-1021/implement-export-evaluation-button)
=> fix(frontend): added export button on evaluation

agenta-backend/agenta_backend/services/db_manager.py
This PR fixes the deployment history by filtering environment revisions in ascending order.
Closes [AGE-1060](https://linear.app/agenta/issue/AGE-1060/[bug]-history-of-environment-messy).
- Create an app from the CLI or UI Template.
- Create a new variant with a different prompt.
- Deploy the new variant to the default environment (production).
- Deploy the default variant to the same default environment (production).
The deployment history should be presented in ascending order.
=> [Bug Fix]: Filter environment revisions by ascending order

agenta-backend/agenta_backend/migrations/mongo_to_postgres/docker-compose.migration.yml, agenta-backend/agenta_backend/resources/templates/templates.py, agenta-backend/agenta_backend/services/templates_manager.py, docker-compose.gh.yml, docker-compose.prod.yml, docker-compose.test.yml, docker-compose.yml
We want to remove the list of the templates from being hosted in a public s3 bucket as there is no valid reason for having it there. As a result we are moving the list of templates to the backend.
A related PR for commons: https://github.com/Agenta-AI/agenta-commons/pull/122
Issue: https://linear.app/agenta/issue/AGE-1084/
=> Move templates to backend

agenta-web/src/components/Layout/ThemeContextProvider.tsx, agenta-web/src/styles/tokens/antd-themeConfig.json
This PR aims to fix the font-family issue we have in some of our domains.
Closes [AGE-1085](https://linear.app/agenta/issue/AGE-1085/[bug]-font-issues-in-cloudstaging)
=> fix(frontend): font style issue

agenta-backend/agenta_backend/services/evaluation_service.py
This PR fixes a bug that caused a keyword argument error when attempting to call `delete_human_evaluation` after encountering a `KeyError` during the creation of a human annotation.
- Adjusted the `delete_human_evaluation` function call to ensure the correct keyword arguments are passed.
1. Create a new app using the `simple_prompt` template on the UI.
2. Update the test set key `country` to `name_of_country`.
3. Create a human annotation.
You should encounter the following error:
```txt
400: Columns in the test set should match the names of the inputs in the variant. Inputs names in variant are: ['country'] while columns in test set are: ['name_of_country'] 
```
Instead of this:
```txt
delete_human_evaluation() got an unexpected keyword argument 'project_id'
```
=> [Bug Fix]: Resolve keyword argument error when deleting human evaluation after KeyError in annotation creation

agenta-cli/agenta/client/backend/core/pydantic_utilities.py, agenta-cli/pyproject.toml
This PR removes the Pydantic warnings on the CLI.
Closes [AGE-1059](https://linear.app/agenta/issue/AGE-1059/remove-warnings-when-using-the-cli).
- Install the pre-release version of agenta==0.25.4a4
- Create an app from the CLI
- Serve the app to either cloud prod, beta or staging (any environment is fine)
- Verify that there are no CLI warnings on your terminal.
=> [Enhancement]: Remove Pydantic warnings in CLI

agenta-backend/agenta_backend/routers/container_router.py
https://github.com/Agenta-AI/agenta/pull/2035/files?diff=split&w=0 introduced a bug in `containers/container_url` endpoint by removing a tab. This PR fixes that
=> Hot fix container_router

docs/blog/main.mdx
=> docs(app): changelog 0.26

agenta-web/cypress/support/commands/evaluations.ts
This PR aims to fix all the e2e test fails in front-end due to recent name changes.
=> test(frontend): fixed e2e test fails

agenta-web/src/components/pages/observability/components/StatusRenderer.tsx
This PR aims to fix the status render issue in the observability table
Closes [AGE-1185](https://linear.app/agenta/issue/AGE-1185/success-status-are-shown-as-initiated-in-the-ui)
=> fix(frontend): observability status render issue

agenta-web/src/pages/apps/[app_id]/observability/index.tsx
Closes [AGE-1180](https://linear.app/agenta/issue/AGE-1180/popoever-in-observability-table-take-sometimes-too-long-to-appear)
=> (frontend)[1180]: Popover in observability table take sometimes too long to appear

agenta-web/src/pages/apps/[app_id]/observability/index.tsx
This PR aims to fix the trace llm tab issue in the observability header.
Closes [AGE-1176](https://linear.app/agenta/issue/AGE-1176/llm-view-in-observability-table-is-showing-grouped-traces-instead-of)
=> fix(frontend): observability LLM traceTab issue

agenta-web/src/components/pages/observability/components/DeleteTraceModal.tsx, agenta-web/src/components/pages/observability/drawer/TraceHeader.tsx, agenta-web/src/services/observability/core/index.ts
Closes [AGE-1177](https://linear.app/agenta/issue/AGE-1177/delete-trace-functionality-does-not-work)
=> (frontend)[Age 1177]: Delete trace functionality does not work

agenta-web/src/contexts/observability.context.tsx, agenta-web/src/pages/apps/[app_id]/observability/index.tsx, agenta-web/src/services/observability/core/index.ts
This PR aims to fix the query states state-management issue by moving up all the query states in the observability-context file.
Closes [AGE-1196](https://linear.app/agenta/issue/AGE-1196/move-all-the-query-states-to-the-contextapi-for-better-state)
- All filters, windowing, and pagination should work as expected.
- Apply a filter, delete the trace, and view the updated data.
=> fix(frontend): moved all the query states in the context-api

agenta-web/src/components/pages/observability/components/AccordionTreePanel.tsx
Closes [AGE-1137](https://linear.app/agenta/issue/AGE-1137/update-design-for-jsonyaml-switch-different)
=> (frontend)[Age 1137]: Update design for JSON/YAML switch different

agenta-web/src/components/pages/observability/drawer/TraceContent.tsx, agenta-web/src/components/pages/observability/drawer/TraceTree.tsx, agenta-web/src/lib/helpers/formatters.ts, agenta-web/src/pages/apps/[app_id]/observability/index.tsx
Closes [AGE-1178](https://linear.app/agenta/issue/AGE-1178/wrong-latency-shown-in-table-and-drawer)
=> (frontend)[Age 1178]Wrong latency shown in table and drawer

agenta-web/src/pages/apps/[app_id]/observability/index.tsx
This PR aims to fix the observability tables columns arrangement for better experience.
Closes [AGE-1184](https://linear.app/agenta/issue/AGE-1184/changing-the-order-for-columns)
=> fix(frontend): rearranged observability table columns

agenta-web/src/components/Filters/Filters.tsx, agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
This PR aims to fix the naming style of the options in the observability filter column select component. And also renamed the table `latency` column to `duration`.
=> fix(frontend): observability filter column names style

agenta-backend/agenta_backend/routers/app_router.py, agenta-backend/agenta_backend/services/app_manager.py
This PR contains changes that act as a dependency to https://github.com/Agenta-AI/agenta-commons/pull/124
=> [Dependency]: Access control in API Keys

.github/dependabot.yml
This PR is to limit Dependabot to only security updates and not creating PRs whenever a dependency is bumped!
=> limit dependabot to only security udates

docs/package-lock.json, docs/package.json
path-to-regexp is a dependency of dependency and is causing a vulnerability issue with the some of the used versions
That's why we need to enforce the version used by using the overrides option in the package.json
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
=> fix path-to-regexp

agenta-backend/poetry.lock, agenta-backend/pyproject.toml
Fastapi was using a starlette version that is causing the vulnerability in the attached screenshot.
Fastapi fixed this in [115.3](https://github.com/fastapi/fastapi/releases/tag/0.115.3) versions hence upgrading our fastapi's version
><img width="1331" alt="Screenshot 2024-11-07 at 15 31 01" src="https://github.com/user-attachments/assets/ebee535a-de20-4bb1-b753-05357f35e39f">
><img width="865" alt="Screenshot 2024-11-07 at 15 29 33" src="https://github.com/user-attachments/assets/130adac5-5bea-4318-8097-a1d1b0041c80">
=> Fix starlette vulnerability

agenta-web/src/components/Filters/Sort.tsx, agenta-web/src/contexts/observability.context.tsx
This PR aims to fix the broken observability windowing logic, allowing users to select either a start time, an end time, or both. Additionally, it improves the format of the date selection component to match the time format used in the table.
Closes [AGE-1267](https://linear.app/agenta/issue/AGE-1267/bug-time-windowing-custom-datetime-validation-is-broken)
=> fix(frontend): broken observability windowing logic and format

agenta-web/src/components/pages/observability/drawer/TraceContent.tsx, agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
This PR aims to fix the observability trace drawer time, cost, etc, font style by changing the `inter` to `mono` font style.
Closes [AGE-1271](https://linear.app/agenta/issue/AGE-1271/improvement-use-mono-font-for-typed-data-amount-datetime-etc)
=> fix(frontend): trace drawer time, cost font style

agenta-web/src/components/pages/evaluations/evaluationScenarios/EvaluationScenarios.tsx
This PR aims to fix the evaluation delete redirection URL.
Closes [AGE-1248](https://linear.app/agenta/issue/AGE-1248/bug-when-deleting-an-evaluation-from-the-evaluation-results-page)
=> fix(frontend): delete evaluation redirection url

agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
Closes [AGE-1270](https://linear.app/agenta/issue/AGE-1270/bug-raw-data-missing-data-in-overview-is-disturbing)
=> (frontend)[Age 1270]: Raw data missing data in overview

agenta-web/src/components/pages/overview/variants/VariantDrawer.tsx
Closes [AGE-1243](https://linear.app/agenta/issue/AGE-1243/bug-in-overview-variant-details-fails-to-open-after-updating-a-variant)
=> (frontend)[Age 1243]: Variant details fails to open after updating a variant

agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/Messages.tsx
This PR aims to remove the autocomplete feature from the Monaco editor in LLM as a judge evaluator
Closes [AGE-1257](https://linear.app/agenta/issue/AGE-1257/bug-remove-autocomplete-from-llm-as-a-judge-configuration-uiasas)
=> fix(frontend): removed autocomplete from llm as a judge

agenta-web/src/components/Evaluations/EvaluationCardView/EvaluationVotePanel.tsx
Closes [AGE-1262](https://linear.app/agenta/issue/AGE-1262/bug-values-that-are-set-to-0-are-lost-when-exiting-and-re-entering)
=> (frontend)[AGE-1262]: Values that are set to 0 are lost when exiting and re-entering

agenta-web/src/components/pages/evaluations/autoEvaluation/EvaluatorsModal/ConfigureEvaluator/Messages.tsx
Closes [AGE-1258](https://linear.app/agenta/issue/AGE-1258/bug-highlighting-of-variables-in-llm-as-a-judge-is-functional-but)
=> (frontend)[AGE-1258]: Highlighting of variables in LLM-as-a-Judge is functional but coloring is buggy

agenta-backend/agenta_backend/routers/app_router.py
This PR aims to fix the predefined app environment list order so that it maintains consistency.
Closes [AGE-1242](https://linear.app/agenta/issue/AGE-1242/qli-environments-with-predefined-names-in-the-wrong-order)
=> fix(backend): predefined app environment order

agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
This PR aims to fix the observability export data format so that we can maintain the consistency.
=> fix(frontend): observability export data format

.github/workflows/bump-versions.yml
- Move creating a tag to a different job and make it after creating the PR
- Make branch name and tag name different to avoid conflicts
=> Fix bump workflow

agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
Closes [AGE-1342](https://linear.app/agenta/issue/AGE-1342/auto-refresh-observability-tables)
=> (frontend)[AGE-1342]: Auto-refresh observability tables

agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx
This PR aims to fix the observability input column data in export results.
- Closes [AGE-1372](https://linear.app/agenta/issue/AGE-1372/[bug]-when-exporting-traces-in-observabillity-the-input-column)
- Closes #2294
=> fix(frontend): observability input column data in export results

agenta-backend/agenta_backend/services/evaluators_service.py
This PR fixes an edge case in llm as a judge.
The function `async def auto_ai_critique` prepares the inputs for the llm-as-a-judge. One of the thing it does is preparing the input prompt of the application, which can be then used in the prompt of the llm-as-a-judge.
What is does it that it fills the variables in that prompt. However that does not work in the case of custom workflows, since sometimes the variables of the prompt are not available to the app (they are substeps).
I have removed the formatting of that string and resolved the problem.
This variable anyways is useless. Since it assumes the prompt is in a variable called prompt_user, it is only kept for now for backward compatibility.
=> fix edge case llm-as-a-judge

.github/actions/check-app-accessibility/action.yml, .github/workflows/cli-commands-tests.yml, agenta-backend/README.md, agenta-cli/pyproject.toml
This PR updates the CLI commands workflow to set the working directory to `examples/deprecated_sdk_v2/`.
=> [Bug Fix]: Resolve CLI commands failing tests

agenta-backend/agenta_backend/models/shared_models.py
This PR ensures that the `input_value` of human evaluation scenario input and output are of type 'Any'.
=> [Bug Fix]: Cannot run human evaluation for mflix app

agenta-web/src/components/Playground/Views/TestView.tsx, agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx, agenta-web/src/components/pages/observability/drawer/TraceContent.tsx, agenta-web/src/components/pages/observability/drawer/TraceTree.tsx
Closes [AGE-1374](https://linear.app/agenta/issue/AGE-1374/[bug]-regression-wrong-time-shown-in-traces)
=> (frontend)[AGE-1374]: Regression wrong time shown in traces

agenta-web/src/components/pages/evaluations/autoEvaluation/AutoEvaluation.tsx
Closes [AGE-1398](https://linear.app/agenta/issue/AGE-1398/[bug]-you-should-not-be-able-to-open-a-running-evaluation)
=> (frontend)[AGE-1398]: You should not be able to open a running evaluation

agenta-web/src/components/GenericDrawer/index.tsx, agenta-web/src/components/pages/observability/ObservabilityDashboard.tsx, agenta-web/src/components/pages/observability/drawer/TestsetDrawer.tsx, agenta-web/src/components/pages/observability/drawer/TraceContent.tsx, agenta-web/src/lib/helpers/utils.ts
This PR aims to add a feature to save observability traces as testset.
Closes [AGE-1337](https://linear.app/agenta/issue/AGE-1337/implement-add-to-test-set-drawer)
1. **Verify Traces**: Ensure traces are visible in the Observability section.  
2. **Select Traces and Open Test Set Drawer**: Select multiple traces using checkboxes and click **'Add Test Set'** to open the drawer.  
3. **Choose or Create Test Set**:  
- Select an existing Test Set or create a new one.  
- Use the **Data Preview** dropdown to view your selected traces and confirm trace keys are automatically mapped in the **Mapping** section.  
4. **Manage Columns**:  
- For existing Test Sets, select columns; for new Test Sets, add column names.  
- Ensure a **warning** appears if duplicate columns are selected.  
5. …
=> [Feat]: implement Test set drawer UI

agenta-web/src/components/Sidebar/Sidebar.tsx
Closes [AGE-1419](https://linear.app/agenta/issue/AGE-1419/[bug]-logout-region-in-the-drop-down-unclickable)
https://github.com/Agenta-AI/agenta_cloud/pull/501
=> fix(frontend): logout button unclickable issue

agenta-web/src/components/NoMobilePageWrapper/NoMobilePageWrapper.tsx, agenta-web/src/components/NoMobilePageWrapper/assets/constants.ts, agenta-web/src/hooks/useResizeObserver.ts, agenta-web/src/pages/_app.tsx
closes [AGE-1407](https://linear.app/agenta/issue/AGE-1407/not-optimized-for-mobile-warning-screen)
- new component has been created to display a message to users accessing Agenta from browsers with narrow viewports.
- minor improvement to the shared useResizeObserver hook so that it can observe an element passed as an argument. Useful to observe window size changes
=> [Feature]: Display a "Not Optimized for Mobile" overlay to users trying to access Agenta app from browsers with narrow width 

agenta-backend/agenta_backend/services/app_manager.py
The code was buggy, however by chance logger.debug was not being executed
=> fix(backend): fixes the debug line, fstring not working

agenta-backend/agenta_backend/services/llm_apps_service.py
This PR resolves an issue where evaluations fail in `cloud.beta` due to a missing `metrics` attribute in the `SpanDTO`. The issue stemmed from the templates using an outdated version of the SDK, which prevented the computation of duration and latency for evaluation runs, leading to errors.  
The templates have been updated to use the latest SDK version. Additionally, a fail-safe logic has been implemented to compute the duration using the `TimeDTO`, ensuring evaluations can proceed without errors even if the `metrics` attribute is unavailable.  
Closes [AGE-1448](https://linear.app/agenta/issue/AGE-1448/[sdk-x-evaluations]-missing-metrics-attribute-in-spandto-causes)
=> [Enhancement]: Add fail-safe logic to compute duration when running evaluations

agenta-backend/agenta_backend/services/app_manager.py, agenta-backend/agenta_backend/services/docker_utils.py, docker-compose.gh.yml, docker-compose.yml, docs/docs/self-host/host-locally.mdx
Closes #1909 
Closes #1915
Closes #1907
In each step we need to test whether, we can create an app, we can interact with it in the playground, we can run an eval on it.
=> Running Agenta on different ports

agenta-cli/agenta/cli/main.py, agenta-cli/agenta/sdk/decorators/routing.py, agenta-cli/agenta/sdk/utils/helpers.py, agenta-cli/pyproject.toml
This PR enhances the debugging process by displaying the current SDK version directly in the deployed application openapi.json. Previously, identifying the SDK version after deploying to cloud templates (staging or beta) required a lengthy process involving manual steps through AWS and CloudWatch logs.
Closes [AGE-1449](https://linear.app/agenta/issue/AGE-1449/display-sdk-version-in-agenta-playground-interface)
=> [Enhancement]: Display SDK Version in Deployed Applications (openapi.json)

agenta-web/src/components/Layout/Layout.tsx
Jam Recording: https://jam.dev/c/2c9d927b-52c7-4d8d-b95d-a718d44d8e66
The problem occurs because we switched workspaces in this example to `DEMO_WORKSPACE`. When clicking the browser's back button, it attempts to load an app at `/apps/ADD_ID/traces` that belongs to the previous workspace, which doesn’t exist in the current workspace
Closes [AGE-1461](https://linear.app/agenta/issue/AGE-1461/[bug]-window-not-responding-after-switching-between-workspaces-while)
=> (frontend)[AGE-1461]: Window not responding after switching between workspaces while in an app

agenta-web/src/hooks/useIsomorphicLayoutEffect.ts, agenta-web/src/hooks/usePostHogAg.ts
closes [AGE-1464](https://linear.app/agenta/issue/AGE-1464/eliminate-console-warnings-about-using-uselayouteffect-on-server)
- introduced a useIsomorphicLayoutEffect hook
```
// useIsomorphicLayoutEffect is a custom hook that uses useLayoutEffect on the client-side
// (when window is defined) and useEffect on the server-side (when window is undefined).
// This ensures that the code runs correctly in both client-side and server-side environments.
```
I guess the only test is to check that this warning is not getting logged to terminal
=> (frontend)[AGE-1464]: implement useIsomorphicLayoutEffect hook to prevent using useLayoutEffect on server

agenta-backend/agenta_backend/services/app_manager.py
- Added a new environment variable when the app is started `AGENTA_RUNTIME`
- This allows users to use fetch the configuration from the backend when the app is running locally and from the route when it's running in agenta cloud
```
if os.getenv("AGENTA_RUNTIME", "false") == "true":
config = ag.ConfigManager.get_from_route(Config)
else:
config = ag.ConfigManager.get_from_registry(
app_slug="my-app", environment_slug="production"
)
```
=> Apps running in agenta have AGENTA_RUNTIME=true

agenta-web/src/lib/helpers/analytics/AgPosthogProvider.tsx, agenta-web/src/lib/helpers/analytics/hooks/usePostHogAg.ts
closes [AGE-1418](https://linear.app/agenta/issue/AGE-1418/improve-posthog-imports)
- In the initial implementation, we couldn't access `getSurveys` which led to an infinite rendering loop during testing. This PR fixes that.
=> fix(frontend): Fix posthog hook to keep getSurveys functionality

agenta-web/src/components/pages/observability/components/AccordionTreePanel.tsx, agenta-web/src/components/pages/observability/drawer/TraceContent.tsx
Closes [AGE-1392](https://linear.app/agenta/issue/AGE-1392/[bug]-fix-scroll-propagation-issue-in-trace-drawer-with-monaco-editor)
=> (frontend)[Age 1392]: Fix Scroll Propagation Issue in Trace Drawer with Monaco Editor

agenta-web/src/components/Layout/Layout.tsx
The issues reported after the QA testing of release checkpoint 1, was caused by rendering pages without full context information. On cloud, this led to queries to the backend using default projectId, and broke first landing on pages that required this data.
- we are now preventing rendering page components if we don't have `appId` or `project` values
=> fix(frontend): Prevent rendering pages without required context information

agenta-web/src/components/pages/settings/Secrets/Secrets.tsx
When you delete a secret, and try to create/add a new one, the request [fails](https://www.awesomescreenshot.com/video/35015204?key=8c690e749450befb1aad2f908aa03e1e) with a 404. But when you reload the page, and try to create/add a new one, it works. I think that in the first instance, the state saves the deleted secret id which results to a 404.
=> (frontend)[Vault Hot Fix]: Stale secret state causing 404 when adding secrets after deletion

agenta-web/src/components/ProtectedRoute/ProtectedRoute.tsx
During my implementation of new tests, I'd encountered a few cases, where the redirection logic inside ProtectedRoute was cancelling direction of new users to `/post-signup` 
- ProtectedRoute now listens to router events and do not perform a push, if router is already in progress of changing routes
=> [Fix] Prevent redirection from ProtectedRoute component if there's another route change is already happening

agenta-web/package-lock.json, agenta-web/package.json, agenta-web/src/lib/helpers/agGrid.tsx
Fixes the issue where clicking "Export as CSV" in the evaluation results view did not trigger a download.
**Changes:**
- Installed `@ag-grid-community/csv-export` package
- Registered `CsvExportModule` from `@ag-grid-community/csv-export` to enable CSV export
- Updated dynamic import of `AgGridReact` to include required module registrations (`ClientSideRowModelModule` and `CsvExportModule`)
Closes #2418
=> (frontend)[Issue 2418]: Evaluation results cannot be downloaded as CSV

agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/helpers.ts, agenta-web/src/lib/hooks/useStatelessVariant/middlewares/appSchemaMiddleware.ts, agenta-web/src/services/api.ts
- cache was not being updated due to old transformer not taking into account the `uri` key.
- also improved the case where we return cached data instead of performing a refetch
=> Frontend [AGE-1340]: Fix cache related issue that is breaking human a/b eval

agenta-web/src/components/NewPlayground/hooks/usePlayground/assets/inputHelpers.ts
closes [AGE-1516](https://linear.app/agenta/issue/AGE-1516/fix-single-bracket-dynamic-variable-identification-in-the-new)
=> [Fix] single bracket variable detection in the new playground

agenta-web/src/components/Editor/Editor.tsx, agenta-web/src/components/NewPlayground/assets/utilities/genericTransformer/utilities/string.ts, agenta-web/src/lib/hooks/useStatelessVariant/assets/genericTransformer/utilities/string.ts
Cloud branch: [hot-fix/-replaced-crypto.random-with-uuidv4-for-id-generation_v2](https://github.com/Agenta-AI/agenta_cloud/tree/hot-fix/-replaced-crypto.random-with-uuidv4-for-id-generation_v2)
=> [Hot Fix]: Replace crypto.randomUUID with uuidv4 for ID generation

agenta-web/src/components/Sidebar/Sidebar.tsx, agenta-web/src/components/Sidebar/hooks/useDropdownItems/index.tsx, agenta-web/src/components/Sidebar/hooks/useDropdownItems/types.d.ts
This PR updates the logic for filtering organizations linked to projects while ensuring that demo projects are excluded.
=> [Hot Fix]: Filtering of non-demo project organizations

agenta-web/src/lib/hooks/useStatelessVariant/middlewares/appSchemaMiddleware.ts
Closes [AGE-1540](https://linear.app/agenta/issue/AGE-1540/[bug]-latest-variant-version-is-not-shown-in-the-configure-evaluator)
=> [AGE-1540](frontend): Latest variant version is not shown in the Configure evaluator

agenta-backend/agenta_backend/services/evaluators_service.py
Closes: AGE-1537 
Closes: #2497
The issue was that the setting values were not 1) propagated to the evaluation function when the call came from the backend 2) the `json_field` was not used to extract the field from the json. This PR fixes both issues
The following has been tested:
- Regression: removing the settings from the input and making sure the new sanity checks work and propagate to the backend
- The evaluator work when run from the backend in case of True (field exists and it is the same as correct_asnwer)
- Works, in case the llm output is not json
- Works, in case the llm output does not contain the field
- Works in case the llm output contains the field but the result is not different
What is still to be QA'ed:
- Does the interface work from the UI test interface in cloud
=> Fix JSON field match
